// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'zh'

export type Locales =
	| 'en'
	| 'ru'
	| 'zh'
	| 'zh-TW'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	settings: {
		communityPlugin: {
			/**
			 * 第​三​方​插​件
			 */
			name: string
			enable: {
				/**
				 * 启​用​功​能
				 */
				name: string
				/**
				 * 为​没​有​图​标​的​第​三​方​插​件​设​置​添​加​图​标
				 */
				desc: string
			}
			searchResults: {
				/**
				 * 在​搜​索​结​果​中​显​示​图​标
				 */
				name: string
				/**
				 * 在​设​置​搜​索​结​果​中​显​示​插​件​图​标​（​仅​在​ ​O​b​s​i​d​i​a​n​ ​1​.​1​3​.​0​+​ ​生​效​）
				 */
				desc: string
			}
			'default': {
				/**
				 * 默​认​图​标
				 */
				name: string
				/**
				 * 为​没​有​图​标​的​第​三​方​插​件​设​置​添​加​默​认​图​标
				 */
				desc: string
				/**
				 * 重​置
				 */
				resetTooltip: string
				/**
				 * 随​机
				 */
				dicesTooltip: string
			}
			search: {
				/**
				 * 输​入​插​件​名​称​.​.​.
				 */
				placeholder: string
				/**
				 * 未​找​到​匹​配​的​插​件
				 */
				noneFound: string
				/**
				 * 重​置​所​有​为​默​认​图​标
				 */
				resetTooltip: string
				/**
				 * 随​机​所​有​图​标
				 */
				dicesTooltip: string
			}
			pluginList: {
				/**
				 * 插​件​列​表
				 */
				name: string
				/**
				 * 为​没​有​图​标​的​第​三​方​插​件​添​加​自​定​义​图​标​（​修​复​ ​O​b​s​i​d​i​a​n​ ​v​1​.​1​1​.​0​）
				 */
				desc: string
				/**
				 * 重​置​为​默​认​图​标
				 */
				resetTooltip: string
				/**
				 * 随​机​图​标
				 */
				dicesTooltip: string
			}
		}
		ribbon: {
			/**
			 * R​i​b​b​o​n​ ​侧​边​栏
			 */
			name: string
			enable: {
				/**
				 * 启​用​功​能
				 */
				name: string
				/**
				 * 为​左​侧​ ​R​i​b​b​o​n​ ​按​钮​自​定​义​图​标
				 */
				desc: string
			}
			list: {
				/**
				 * 按​钮​列​表
				 */
				name: string
				/**
				 * 为​ ​R​i​b​b​o​n​ ​按​钮​分​配​图​标​（​按​按​钮​提​示​文​本​识​别​）
				 */
				desc: string
				/**
				 * 未​找​到​ ​R​i​b​b​o​n​ ​按​钮
				 */
				noneFound: string
				/**
				 * 重​置​为​原​始​图​标
				 */
				resetTooltip: string
				/**
				 * 刷​新​列​表
				 */
				refreshTooltip: string
				/**
				 * 已​有​图​标
				 */
				hasIcon: string
				/**
				 * 无​图​标
				 */
				noIcon: string
				/**
				 * 已​自​定​义
				 */
				customized: string
			}
		}
		experimental: {
			/**
			 * 实​验​性
			 */
			name: string
			keepPluginFirst: {
				/**
				 * 始​终​最​先​加​载​本​插​件
				 */
				name: string
				/**
				 * 自​动​把​本​插​件​保​持​在​ ​.​o​b​s​i​d​i​a​n​/​c​o​m​m​u​n​i​t​y​-​p​l​u​g​i​n​s​.​j​s​o​n​ ​数​组​首​位​（​社​区​插​件​按​此​顺​序​加​载​）​，​避​免​其​他​插​件​因​加​载​顺​序​出​现​图​标​空​白​。​每​次​启​用​/​禁​用​插​件​后​ ​O​b​s​i​d​i​a​n​ ​会​重​写​该​数​组​，​本​功​能​会​在​本​插​件​加​载​时​自​动​修​正​。​仅​调​整​顺​序​、​不​增​删​条​目​；​对​当​前​会​话​无​效​，​下​次​启​动​生​效​。​实​验​性​功​能​，​如​出​现​异​常​请​关​闭​。
				 */
				desc: string
			}
		}
	}
	common: {
		/**
		 * 保​存
		 */
		save: string
		/**
		 * 添​加
		 */
		add: string
		/**
		 * 编​辑
		 */
		edit: string
		/**
		 * 删​除
		 */
		'delete': string
		/**
		 * 取​消
		 */
		cancel: string
	}
	view: {
		CustomIconLib: {
			/**
			 * 自​定​义​图​标​库
			 */
			name: string
			/**
			 * 打​开​自​定​义​图​标​库
			 */
			command: string
			/**
			 * 重​新​应​用​所​有​图​标
			 */
			reapplyCommand: string
			/**
			 * 已​重​新​应​用​所​有​自​定​义​图​标
			 */
			reapplyNotice: string
			/**
			 * 搜​索​图​标​.​.​.
			 */
			searchPlaceholder: string
			svg: {
				/**
				 * S​V​G​（​实​验​性​）
				 */
				tabName: string
				/**
				 * 复​制​ ​S​V​G​ ​代​码
				 */
				copyAction: string
				modal: {
					/**
					 * 粘​贴​源​码
					 */
					pasteMode: string
					/**
					 * 上​传​文​件
					 */
					uploadMode: string
					/**
					 * 图​标​I​D​ ​(​例​如​:​ ​m​y​-​i​c​o​n​)
					 */
					idPlaceholder: string
					/**
					 * S​V​G​ ​内​容​ ​(​<​s​v​g​>​.​.​.​<​/​s​v​g​>​)
					 */
					contentPlaceholder: string
					/**
					 * 选​择​ ​S​V​G​ ​文​件
					 */
					selectFiles: string
					/**
					 * 可​以​选​择​多​个​ ​S​V​G​ ​文​件​进​行​批​量​添​加​，​将​使​用​文​件​名​作​为​图​标​ ​I​D​。
					 */
					selectFilesDesc: string
					/**
					 * 已​选​择​ ​{​c​o​u​n​t​}​ ​个​文​件
					 * @param {number} count
					 */
					selectedFiles: RequiredParams<'count'>
				}
			}
			pack: {
				/**
				 * 图​标​库
				 */
				tabName: string
				/**
				 * 正​在​下​载​图​标​库​…
				 */
				installing: string
				/**
				 * 正​在​下​载​图​标​ ​{​d​o​n​e​}​/​{​t​o​t​a​l​}​…
				 * @param {number} done
				 * @param {number} total
				 */
				progress: RequiredParams<'done' | 'total'>
				/**
				 * 已​安​装​ ​{​c​o​u​n​t​}​ ​个​图​标​，​立​即​生​效
				 * @param {number} count
				 */
				installed: RequiredParams<'count'>
				/**
				 * 图​标​库​安​装​失​败
				 */
				installFailed: string
				/**
				 * 图​标​数
				 */
				iconCount: string
				/**
				 * 许​可​证
				 */
				licenseLabel: string
				/**
				 * 图​标​ ​I​D​ ​前​缀
				 */
				idLabel: string
				/**
				 * 来​源​包
				 */
				sourcePackage: string
				/**
				 * 该​图​标​集​包​含​ ​{​c​o​u​n​t​}​ ​个​图​标​，​体​积​较​大​，​安​装​与​同​步​耗​时​可​能​较​长​，​确​定​继​续​？
				 * @param {number} count
				 */
				bigPackWarning: RequiredParams<'count'>
				/**
				 * 安​装​完​成​后​图​标​存​储​在​本​地​，​离​线​可​用​。
				 */
				offlineHint: string
				npmModal: {
					/**
					 * 自​定​义​ ​n​p​m​ ​图​标​包
					 */
					title: string
					/**
					 * 包​ ​I​D​（​小​写​字​母​/​数​字​/​连​字​符​，​如​ ​m​y​-​i​c​o​n​s​）
					 */
					packIdPlaceholder: string
					/**
					 * n​p​m​ ​包​名​（​如​ ​@​t​a​b​l​e​r​/​i​c​o​n​s​）
					 */
					packagePlaceholder: string
					/**
					 * S​V​G​ ​路​径​ ​g​l​o​b​（​如​ ​i​c​o​n​s​/​o​u​t​l​i​n​e​/​*​.​s​v​g​）
					 */
					globPlaceholder: string
					/**
					 * 版​本​（​可​选​，​默​认​最​新​）
					 */
					versionPlaceholder: string
					/**
					 * 从​ ​n​p​m​ ​C​D​N​ ​抓​取​包​内​散​装​ ​S​V​G​ ​文​件​；​支​持​ ​*​、​*​*​ ​与​逗​号​分​组​多​选​一​语​法​。
					 */
					hint: string
				}
				/**
				 * 将​删​除​ ​{​c​o​u​n​t​}​ ​个​图​标​（​本​地​文​件​与​设​置​清​单​）​，​已​使​用​该​图​标​的​界​面​将​回​退​为​空​白​。
				 * @param {number} count
				 */
				uninstallHint: RequiredParams<'count'>
				/**
				 * 图​标​库​卸​载​失​败
				 */
				uninstallFailed: string
				/**
				 * 刷​新​目​录
				 */
				refreshTooltip: string
				/**
				 * 已​安​装
				 */
				installedSection: string
				/**
				 * 尚​未​安​装​任​何​图​标​库​，​从​下​方​目​录​选​择​安​装​。
				 */
				noPacksInstalled: string
				/**
				 * {​c​o​u​n​t​}​ ​个​图​标
				 * @param {number} count
				 */
				iconCountLabel: RequiredParams<'count'>
				/**
				 * 浏​览​图​标
				 */
				browseTooltip: string
				/**
				 * 启​用​/​停​用​该​图​标​库
				 */
				enabledTooltip: string
				/**
				 * 图​标​集​目​录​（​I​c​o​n​i​f​y​，​2​2​0​+​ ​集​）
				 */
				catalogSection: string
				/**
				 * 目​录​缓​存​于​ ​{​t​i​m​e​}
				 * @param {unknown} time
				 */
				cachedAt: RequiredParams<'time'>
				/**
				 * 离​线​缓​存
				 */
				catalogCached: string
				/**
				 * 在​线
				 */
				catalogOnline: string
				/**
				 * 图​标​集​目​录​加​载​失​败​（​网​络​不​可​用​且​无​缓​存​）
				 */
				catalogLoadFailed: string
				/**
				 * 正​在​加​载​图​标​集​目​录​…
				 */
				catalogLoading: string
				/**
				 * 常​用​ ​n​p​m​ ​图​标​包​（​一​键​安​装​）
				 */
				presetsSection: string
				/**
				 * 已​安​装
				 */
				alreadyInstalled: string
				/**
				 * 返​回
				 */
				backTooltip: string
				/**
				 * 只​读​展​示​。​点​击​图​标​可​复​制​完​整​ ​I​D​（​C​I​-​ ​前​缀​）​。
				 */
				detailHint: string
				/**
				 * 预​览
				 */
				previewTitle: string
				/**
				 * 正​在​加​载​预​览​…
				 */
				previewLoading: string
				/**
				 * 暂​无​预​览​样​例
				 */
				previewEmpty: string
				/**
				 * 预​览​加​载​失​败
				 */
				previewFailed: string
				/**
				 * 显​示​更​多​（​{​s​h​o​w​n​}​/​{​t​o​t​a​l​}​）
				 * @param {number} shown
				 * @param {number} total
				 */
				showMore: RequiredParams<'shown' | 'total'>
			}
			lucide: {
				/**
				 * L​u​c​i​d​e
				 */
				tabName: string
				/**
				 * 共​ ​{​c​o​u​n​t​}​ ​个​图​标
				 * @param {number} count
				 */
				count: RequiredParams<'count'>
				/**
				 * 只​读​展​示​。​以​下​为​插​件​内​置​ ​L​u​c​i​d​e​ ​中​ ​O​b​s​i​d​i​a​n​ ​原​生​未​包​含​的​图​标​，​点​击​图​标​可​复​制​名​称​。
				 */
				descHint: string
			}
		}
	}
}

export type TranslationFunctions = {
	settings: {
		communityPlugin: {
			/**
			 * 第三方插件
			 */
			name: () => LocalizedString
			enable: {
				/**
				 * 启用功能
				 */
				name: () => LocalizedString
				/**
				 * 为没有图标的第三方插件设置添加图标
				 */
				desc: () => LocalizedString
			}
			searchResults: {
				/**
				 * 在搜索结果中显示图标
				 */
				name: () => LocalizedString
				/**
				 * 在设置搜索结果中显示插件图标（仅在 Obsidian 1.13.0+ 生效）
				 */
				desc: () => LocalizedString
			}
			'default': {
				/**
				 * 默认图标
				 */
				name: () => LocalizedString
				/**
				 * 为没有图标的第三方插件设置添加默认图标
				 */
				desc: () => LocalizedString
				/**
				 * 重置
				 */
				resetTooltip: () => LocalizedString
				/**
				 * 随机
				 */
				dicesTooltip: () => LocalizedString
			}
			search: {
				/**
				 * 输入插件名称...
				 */
				placeholder: () => LocalizedString
				/**
				 * 未找到匹配的插件
				 */
				noneFound: () => LocalizedString
				/**
				 * 重置所有为默认图标
				 */
				resetTooltip: () => LocalizedString
				/**
				 * 随机所有图标
				 */
				dicesTooltip: () => LocalizedString
			}
			pluginList: {
				/**
				 * 插件列表
				 */
				name: () => LocalizedString
				/**
				 * 为没有图标的第三方插件添加自定义图标（修复 Obsidian v1.11.0）
				 */
				desc: () => LocalizedString
				/**
				 * 重置为默认图标
				 */
				resetTooltip: () => LocalizedString
				/**
				 * 随机图标
				 */
				dicesTooltip: () => LocalizedString
			}
		}
		ribbon: {
			/**
			 * Ribbon 侧边栏
			 */
			name: () => LocalizedString
			enable: {
				/**
				 * 启用功能
				 */
				name: () => LocalizedString
				/**
				 * 为左侧 Ribbon 按钮自定义图标
				 */
				desc: () => LocalizedString
			}
			list: {
				/**
				 * 按钮列表
				 */
				name: () => LocalizedString
				/**
				 * 为 Ribbon 按钮分配图标（按按钮提示文本识别）
				 */
				desc: () => LocalizedString
				/**
				 * 未找到 Ribbon 按钮
				 */
				noneFound: () => LocalizedString
				/**
				 * 重置为原始图标
				 */
				resetTooltip: () => LocalizedString
				/**
				 * 刷新列表
				 */
				refreshTooltip: () => LocalizedString
				/**
				 * 已有图标
				 */
				hasIcon: () => LocalizedString
				/**
				 * 无图标
				 */
				noIcon: () => LocalizedString
				/**
				 * 已自定义
				 */
				customized: () => LocalizedString
			}
		}
		experimental: {
			/**
			 * 实验性
			 */
			name: () => LocalizedString
			keepPluginFirst: {
				/**
				 * 始终最先加载本插件
				 */
				name: () => LocalizedString
				/**
				 * 自动把本插件保持在 .obsidian/community-plugins.json 数组首位（社区插件按此顺序加载），避免其他插件因加载顺序出现图标空白。每次启用/禁用插件后 Obsidian 会重写该数组，本功能会在本插件加载时自动修正。仅调整顺序、不增删条目；对当前会话无效，下次启动生效。实验性功能，如出现异常请关闭。
				 */
				desc: () => LocalizedString
			}
		}
	}
	common: {
		/**
		 * 保存
		 */
		save: () => LocalizedString
		/**
		 * 添加
		 */
		add: () => LocalizedString
		/**
		 * 编辑
		 */
		edit: () => LocalizedString
		/**
		 * 删除
		 */
		'delete': () => LocalizedString
		/**
		 * 取消
		 */
		cancel: () => LocalizedString
	}
	view: {
		CustomIconLib: {
			/**
			 * 自定义图标库
			 */
			name: () => LocalizedString
			/**
			 * 打开自定义图标库
			 */
			command: () => LocalizedString
			/**
			 * 重新应用所有图标
			 */
			reapplyCommand: () => LocalizedString
			/**
			 * 已重新应用所有自定义图标
			 */
			reapplyNotice: () => LocalizedString
			/**
			 * 搜索图标...
			 */
			searchPlaceholder: () => LocalizedString
			svg: {
				/**
				 * SVG（实验性）
				 */
				tabName: () => LocalizedString
				/**
				 * 复制 SVG 代码
				 */
				copyAction: () => LocalizedString
				modal: {
					/**
					 * 粘贴源码
					 */
					pasteMode: () => LocalizedString
					/**
					 * 上传文件
					 */
					uploadMode: () => LocalizedString
					/**
					 * 图标ID (例如: my-icon)
					 */
					idPlaceholder: () => LocalizedString
					/**
					 * SVG 内容 (<svg>...</svg>)
					 */
					contentPlaceholder: () => LocalizedString
					/**
					 * 选择 SVG 文件
					 */
					selectFiles: () => LocalizedString
					/**
					 * 可以选择多个 SVG 文件进行批量添加，将使用文件名作为图标 ID。
					 */
					selectFilesDesc: () => LocalizedString
					/**
					 * 已选择 {count} 个文件
					 */
					selectedFiles: (arg: { count: number }) => LocalizedString
				}
			}
			pack: {
				/**
				 * 图标库
				 */
				tabName: () => LocalizedString
				/**
				 * 正在下载图标库…
				 */
				installing: () => LocalizedString
				/**
				 * 正在下载图标 {done}/{total}…
				 */
				progress: (arg: { done: number, total: number }) => LocalizedString
				/**
				 * 已安装 {count} 个图标，立即生效
				 */
				installed: (arg: { count: number }) => LocalizedString
				/**
				 * 图标库安装失败
				 */
				installFailed: () => LocalizedString
				/**
				 * 图标数
				 */
				iconCount: () => LocalizedString
				/**
				 * 许可证
				 */
				licenseLabel: () => LocalizedString
				/**
				 * 图标 ID 前缀
				 */
				idLabel: () => LocalizedString
				/**
				 * 来源包
				 */
				sourcePackage: () => LocalizedString
				/**
				 * 该图标集包含 {count} 个图标，体积较大，安装与同步耗时可能较长，确定继续？
				 */
				bigPackWarning: (arg: { count: number }) => LocalizedString
				/**
				 * 安装完成后图标存储在本地，离线可用。
				 */
				offlineHint: () => LocalizedString
				npmModal: {
					/**
					 * 自定义 npm 图标包
					 */
					title: () => LocalizedString
					/**
					 * 包 ID（小写字母/数字/连字符，如 my-icons）
					 */
					packIdPlaceholder: () => LocalizedString
					/**
					 * npm 包名（如 @tabler/icons）
					 */
					packagePlaceholder: () => LocalizedString
					/**
					 * SVG 路径 glob（如 icons/outline/*.svg）
					 */
					globPlaceholder: () => LocalizedString
					/**
					 * 版本（可选，默认最新）
					 */
					versionPlaceholder: () => LocalizedString
					/**
					 * 从 npm CDN 抓取包内散装 SVG 文件；支持 *、** 与逗号分组多选一语法。
					 */
					hint: () => LocalizedString
				}
				/**
				 * 将删除 {count} 个图标（本地文件与设置清单），已使用该图标的界面将回退为空白。
				 */
				uninstallHint: (arg: { count: number }) => LocalizedString
				/**
				 * 图标库卸载失败
				 */
				uninstallFailed: () => LocalizedString
				/**
				 * 刷新目录
				 */
				refreshTooltip: () => LocalizedString
				/**
				 * 已安装
				 */
				installedSection: () => LocalizedString
				/**
				 * 尚未安装任何图标库，从下方目录选择安装。
				 */
				noPacksInstalled: () => LocalizedString
				/**
				 * {count} 个图标
				 */
				iconCountLabel: (arg: { count: number }) => LocalizedString
				/**
				 * 浏览图标
				 */
				browseTooltip: () => LocalizedString
				/**
				 * 启用/停用该图标库
				 */
				enabledTooltip: () => LocalizedString
				/**
				 * 图标集目录（Iconify，220+ 集）
				 */
				catalogSection: () => LocalizedString
				/**
				 * 目录缓存于 {time}
				 */
				cachedAt: (arg: { time: unknown }) => LocalizedString
				/**
				 * 离线缓存
				 */
				catalogCached: () => LocalizedString
				/**
				 * 在线
				 */
				catalogOnline: () => LocalizedString
				/**
				 * 图标集目录加载失败（网络不可用且无缓存）
				 */
				catalogLoadFailed: () => LocalizedString
				/**
				 * 正在加载图标集目录…
				 */
				catalogLoading: () => LocalizedString
				/**
				 * 常用 npm 图标包（一键安装）
				 */
				presetsSection: () => LocalizedString
				/**
				 * 已安装
				 */
				alreadyInstalled: () => LocalizedString
				/**
				 * 返回
				 */
				backTooltip: () => LocalizedString
				/**
				 * 只读展示。点击图标可复制完整 ID（CI- 前缀）。
				 */
				detailHint: () => LocalizedString
				/**
				 * 预览
				 */
				previewTitle: () => LocalizedString
				/**
				 * 正在加载预览…
				 */
				previewLoading: () => LocalizedString
				/**
				 * 暂无预览样例
				 */
				previewEmpty: () => LocalizedString
				/**
				 * 预览加载失败
				 */
				previewFailed: () => LocalizedString
				/**
				 * 显示更多（{shown}/{total}）
				 */
				showMore: (arg: { shown: number, total: number }) => LocalizedString
			}
			lucide: {
				/**
				 * Lucide
				 */
				tabName: () => LocalizedString
				/**
				 * 共 {count} 个图标
				 */
				count: (arg: { count: number }) => LocalizedString
				/**
				 * 只读展示。以下为插件内置 Lucide 中 Obsidian 原生未包含的图标，点击图标可复制名称。
				 */
				descHint: () => LocalizedString
			}
		}
	}
}

export type Formatters = {}
