// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable no-irregular-whitespace, @typescript-eslint/ban-types -- auto-generated by typesafe-i18n */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'zh'

export type Locales =
	| 'en'
	| 'ru'
	| 'zh'
	| 'zh-TW'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	settings: {
		communityPlugin: {
			/**
			 * 第​三​方​插​件
			 */
			name: string
			enable: {
				/**
				 * 启​用​功​能
				 */
				name: string
				/**
				 * 为​没​有​图​标​的​第​三​方​插​件​设​置​添​加​图​标
				 */
				desc: string
			}
			searchResults: {
				/**
				 * 在​搜​索​结​果​中​显​示​图​标
				 */
				name: string
				/**
				 * 在​设​置​搜​索​结​果​中​显​示​插​件​图​标​（​仅​在​ ​O​b​s​i​d​i​a​n​ ​1​.​1​3​.​0​+​ ​生​效​）
				 */
				desc: string
			}
			'default': {
				/**
				 * 默​认​图​标
				 */
				name: string
				/**
				 * 为​没​有​图​标​的​第​三​方​插​件​设​置​添​加​默​认​图​标
				 */
				desc: string
				/**
				 * 重​置
				 */
				resetTooltip: string
				/**
				 * 随​机
				 */
				dicesTooltip: string
			}
			search: {
				/**
				 * 输​入​插​件​名​称​.​.​.
				 */
				placeholder: string
				/**
				 * 未​找​到​匹​配​的​插​件
				 */
				noneFound: string
				/**
				 * 重​置​所​有​为​默​认​图​标
				 */
				resetTooltip: string
				/**
				 * 随​机​所​有​图​标
				 */
				dicesTooltip: string
			}
			pluginList: {
				/**
				 * 插​件​列​表
				 */
				name: string
				/**
				 * 为​没​有​图​标​的​第​三​方​插​件​添​加​自​定​义​图​标​（​修​复​ ​O​b​s​i​d​i​a​n​ ​v​1​.​1​1​.​0​）
				 */
				desc: string
				/**
				 * 重​置​为​默​认​图​标
				 */
				resetTooltip: string
				/**
				 * 随​机​图​标
				 */
				dicesTooltip: string
			}
		}
	}
	common: {
		/**
		 * 保​存
		 */
		save: string
		/**
		 * 添​加
		 */
		add: string
		/**
		 * 编​辑
		 */
		edit: string
		/**
		 * 删​除
		 */
		'delete': string
		/**
		 * 取​消
		 */
		cancel: string
	}
	view: {
		CustomIconLib: {
			/**
			 * 自​定​义​图​标​库
			 */
			name: string
			/**
			 * 打​开​自​定​义​图​标​库
			 */
			command: string
			/**
			 * 重​新​应​用​所​有​图​标
			 */
			reapplyCommand: string
			/**
			 * 已​重​新​应​用​所​有​自​定​义​图​标
			 */
			reapplyNotice: string
			/**
			 * 搜​索​图​标​.​.​.
			 */
			searchPlaceholder: string
			svg: {
				/**
				 * S​V​G​（​实​验​性​）
				 */
				tabName: string
				/**
				 * 复​制​ ​S​V​G​ ​代​码
				 */
				copyAction: string
				modal: {
					/**
					 * 粘​贴​源​码
					 */
					pasteMode: string
					/**
					 * 上​传​文​件
					 */
					uploadMode: string
					/**
					 * 图​标​I​D​ ​(​例​如​:​ ​m​y​-​i​c​o​n​)
					 */
					idPlaceholder: string
					/**
					 * S​V​G​ ​内​容​ ​(​<​s​v​g​>​.​.​.​<​/​s​v​g​>​)
					 */
					contentPlaceholder: string
					/**
					 * 选​择​ ​S​V​G​ ​文​件
					 */
					selectFiles: string
					/**
					 * 可​以​选​择​多​个​ ​S​V​G​ ​文​件​进​行​批​量​添​加​，​将​使​用​文​件​名​作​为​图​标​ ​I​D​。
					 */
					selectFilesDesc: string
					/**
					 * 已​选​择​ ​{​c​o​u​n​t​}​ ​个​文​件
					 * @param {number} count
					 */
					selectedFiles: RequiredParams<'count'>
				}
			}
		}
	}
}

export type TranslationFunctions = {
	settings: {
		communityPlugin: {
			/**
			 * 第三方插件
			 */
			name: () => LocalizedString
			enable: {
				/**
				 * 启用功能
				 */
				name: () => LocalizedString
				/**
				 * 为没有图标的第三方插件设置添加图标
				 */
				desc: () => LocalizedString
			}
			searchResults: {
				/**
				 * 在搜索结果中显示图标
				 */
				name: () => LocalizedString
				/**
				 * 在设置搜索结果中显示插件图标（仅在 Obsidian 1.13.0+ 生效）
				 */
				desc: () => LocalizedString
			}
			'default': {
				/**
				 * 默认图标
				 */
				name: () => LocalizedString
				/**
				 * 为没有图标的第三方插件设置添加默认图标
				 */
				desc: () => LocalizedString
				/**
				 * 重置
				 */
				resetTooltip: () => LocalizedString
				/**
				 * 随机
				 */
				dicesTooltip: () => LocalizedString
			}
			search: {
				/**
				 * 输入插件名称...
				 */
				placeholder: () => LocalizedString
				/**
				 * 未找到匹配的插件
				 */
				noneFound: () => LocalizedString
				/**
				 * 重置所有为默认图标
				 */
				resetTooltip: () => LocalizedString
				/**
				 * 随机所有图标
				 */
				dicesTooltip: () => LocalizedString
			}
			pluginList: {
				/**
				 * 插件列表
				 */
				name: () => LocalizedString
				/**
				 * 为没有图标的第三方插件添加自定义图标（修复 Obsidian v1.11.0）
				 */
				desc: () => LocalizedString
				/**
				 * 重置为默认图标
				 */
				resetTooltip: () => LocalizedString
				/**
				 * 随机图标
				 */
				dicesTooltip: () => LocalizedString
			}
		}
	}
	common: {
		/**
		 * 保存
		 */
		save: () => LocalizedString
		/**
		 * 添加
		 */
		add: () => LocalizedString
		/**
		 * 编辑
		 */
		edit: () => LocalizedString
		/**
		 * 删除
		 */
		'delete': () => LocalizedString
		/**
		 * 取消
		 */
		cancel: () => LocalizedString
	}
	view: {
		CustomIconLib: {
			/**
			 * 自定义图标库
			 */
			name: () => LocalizedString
			/**
			 * 打开自定义图标库
			 */
			command: () => LocalizedString
			/**
			 * 重新应用所有图标
			 */
			reapplyCommand: () => LocalizedString
			/**
			 * 已重新应用所有自定义图标
			 */
			reapplyNotice: () => LocalizedString
			/**
			 * 搜索图标...
			 */
			searchPlaceholder: () => LocalizedString
			svg: {
				/**
				 * SVG（实验性）
				 */
				tabName: () => LocalizedString
				/**
				 * 复制 SVG 代码
				 */
				copyAction: () => LocalizedString
				modal: {
					/**
					 * 粘贴源码
					 */
					pasteMode: () => LocalizedString
					/**
					 * 上传文件
					 */
					uploadMode: () => LocalizedString
					/**
					 * 图标ID (例如: my-icon)
					 */
					idPlaceholder: () => LocalizedString
					/**
					 * SVG 内容 (<svg>...</svg>)
					 */
					contentPlaceholder: () => LocalizedString
					/**
					 * 选择 SVG 文件
					 */
					selectFiles: () => LocalizedString
					/**
					 * 可以选择多个 SVG 文件进行批量添加，将使用文件名作为图标 ID。
					 */
					selectFilesDesc: () => LocalizedString
					/**
					 * 已选择 {count} 个文件
					 */
					selectedFiles: (arg: { count: number }) => LocalizedString
				}
			}
		}
	}
}

export type Formatters = {}
