// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'zh'

export type Locales =
	| 'en'
	| 'ru'
	| 'zh'
	| 'zh-TW'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	settings: {
		communityPlugin: {
			/**
			 * 第​三​方​插​件
			 */
			name: string
			enable: {
				/**
				 * 启​用​功​能
				 */
				name: string
				/**
				 * 为​没​有​图​标​的​第​三​方​插​件​设​置​添​加​图​标
				 */
				desc: string
			}
			searchResults: {
				/**
				 * 在​搜​索​结​果​中​显​示​图​标
				 */
				name: string
				/**
				 * 在​设​置​搜​索​结​果​中​显​示​插​件​图​标​（​仅​在​ ​O​b​s​i​d​i​a​n​ ​1​.​1​3​.​0​+​ ​生​效​）
				 */
				desc: string
			}
			'default': {
				/**
				 * 默​认​图​标
				 */
				name: string
				/**
				 * 为​没​有​图​标​的​第​三​方​插​件​设​置​添​加​默​认​图​标
				 */
				desc: string
				/**
				 * 重​置
				 */
				resetTooltip: string
			}
			search: {
				/**
				 * 输​入​插​件​名​称​.​.​.
				 */
				placeholder: string
				/**
				 * 未​找​到​匹​配​的​插​件
				 */
				noneFound: string
				/**
				 * 重​置​所​有​为​默​认​图​标
				 */
				resetTooltip: string
				/**
				 * 随​机​所​有​图​标
				 */
				dicesTooltip: string
			}
			pluginList: {
				/**
				 * 插​件​列​表
				 */
				name: string
				/**
				 * 为​没​有​图​标​的​第​三​方​插​件​添​加​自​定​义​图​标​（​修​复​ ​O​b​s​i​d​i​a​n​ ​v​1​.​1​1​.​0​）
				 */
				desc: string
				/**
				 * 重​置​为​默​认​图​标
				 */
				resetTooltip: string
			}
		}
		ribbon: {
			/**
			 * R​i​b​b​o​n​ ​侧​边​栏
			 */
			name: string
			enable: {
				/**
				 * 启​用​功​能
				 */
				name: string
				/**
				 * 为​左​侧​ ​R​i​b​b​o​n​ ​按​钮​自​定​义​图​标
				 */
				desc: string
			}
			list: {
				/**
				 * 按​钮​列​表
				 */
				name: string
				/**
				 * 为​ ​R​i​b​b​o​n​ ​按​钮​分​配​图​标​（​按​按​钮​提​示​文​本​识​别​）
				 */
				desc: string
				/**
				 * 未​找​到​ ​R​i​b​b​o​n​ ​按​钮
				 */
				noneFound: string
				/**
				 * 重​置​为​原​始​图​标
				 */
				resetTooltip: string
				/**
				 * 刷​新​列​表
				 */
				refreshTooltip: string
				/**
				 * 已​有​图​标
				 */
				hasIcon: string
				/**
				 * 无​图​标
				 */
				noIcon: string
				/**
				 * 已​自​定​义
				 */
				customized: string
			}
		}
		fileExplorer: {
			/**
			 * 文​件​浏​览​器
			 */
			name: string
			enable: {
				/**
				 * 启​用​功​能
				 */
				name: string
				/**
				 * 为​文​件​浏​览​器​中​的​文​件​夹​和​文​件​自​定​义​图​标
				 */
				desc: string
			}
			folderDefault: {
				/**
				 * 文​件​夹​默​认​图​标
				 */
				name: string
				/**
				 * 为​所​有​文​件​夹​设​置​统​一​的​默​认​图​标​（​留​空​则​不​显​示​）
				 */
				desc: string
				/**
				 * 重​置
				 */
				resetTooltip: string
			}
			fileDefault: {
				/**
				 * 文​件​默​认​图​标
				 */
				name: string
				/**
				 * 为​未​匹​配​到​扩​展​名​规​则​的​文​件​设​置​兜​底​图​标​（​留​空​则​不​显​示​）
				 */
				desc: string
				/**
				 * 重​置
				 */
				resetTooltip: string
			}
			inherit: {
				subfolder: {
					/**
					 * 子​文​件​夹​继​承​父​文​件​夹​图​标
					 */
					name: string
					/**
					 * 子​文​件​夹​在​没​有​自​身​配​置​时​，​自​动​套​用​最​近​祖​先​文​件​夹​的​图​标​（​含​颜​色​）
					 */
					desc: string
				}
				file: {
					/**
					 * 子​文​件​继​承​父​文​件​夹​图​标
					 */
					name: string
					/**
					 * 文​件​在​没​有​自​身​配​置​、​也​未​匹​配​扩​展​名​规​则​时​，​套​用​其​所​在​文​件​夹​链​的​最​近​图​标​（​含​颜​色​）
					 */
					desc: string
				}
			}
			extensions: {
				/**
				 * 按​扩​展​名
				 */
				name: string
				/**
				 * 为​某​类​扩​展​名​的​文​件​统​一​分​配​图​标​（​如​ ​p​d​f​、​c​a​n​v​a​s​）​；​支​持​复​合​后​缀​，​如​ ​e​x​c​a​l​i​d​r​a​w​.​m​d​ ​优​先​于​ ​m​d​。​无​扩​展​名​的​文​件​（​如​ ​.​g​i​t​i​g​n​o​r​e​）​请​用​下​方​「​单​项​覆​盖​」​在​文​件​树​中​右​键​设​置​。
				 */
				desc: string
				/**
				 * 支​持​批​量​（​如​ ​.​x​d​b​ ​.​j​s​）​.​.​.
				 */
				placeholder: string
				/**
				 * 添​加​扩​展​名
				 */
				addTooltip: string
				/**
				 * 尚​未​配​置​扩​展​名​规​则
				 */
				noneFound: string
				/**
				 * 筛​选​扩​展​名​.​.​.
				 */
				filterPlaceholder: string
				/**
				 * 没​有​匹​配​的​扩​展​名
				 */
				noneMatched: string
				/**
				 * {​c​o​u​n​t​}​ ​个​文​件
				 * @param {number} count
				 */
				fileCount: RequiredParams<'count'>
				/**
				 * 库​中​暂​无​此​类​文​件
				 */
				noFiles: string
				/**
				 * 未​配​置​图​标​，​此​规​则​不​生​效
				 */
				needIcon: string
				/**
				 * 已​添​加​ ​{​c​o​u​n​t​}​ ​个​扩​展​名
				 * @param {number} count
				 */
				added: RequiredParams<'count'>
				/**
				 * 已​添​加​ ​{​a​d​d​e​d​}​ ​个​，​跳​过​ ​{​s​k​i​p​p​e​d​}​ ​个​（​已​存​在​）
				 * @param {number} added
				 * @param {number} skipped
				 */
				addedSkipped: RequiredParams<'added' | 'skipped'>
				/**
				 * 这​些​扩​展​名​都​已​配​置​过​了
				 */
				allDuplicate: string
				/**
				 * 无​法​识​别​为​扩​展​名​：​{​t​o​k​e​n​s​}
				 * @param {string} tokens
				 */
				invalidInput: RequiredParams<'tokens'>
				/**
				 * 切​换​排​序​（​当​前​：​{​m​o​d​e​}​）
				 * @param {string} mode
				 */
				sortTooltip: RequiredParams<'mode'>
				/**
				 * 按​文​件​数
				 */
				sortByCount: string
				/**
				 * 按​名​称
				 */
				sortByName: string
				/**
				 * 库​中​还​未​配​置​的​扩​展​名
				 */
				candidates: string
				/**
				 * 添​加​ ​.​{​e​x​t​}​（​{​c​o​u​n​t​}​ ​个​文​件​）
				 * @param {number} count
				 * @param {string} ext
				 */
				candidateTooltip: RequiredParams<'count' | 'ext'>
				/**
				 * 随​机​筛​选​出​的​图​标
				 */
				dicesTooltip: string
				/**
				 * 清​空​筛​选​出​的​图​标
				 */
				clearTooltip: string
				/**
				 * 清​空​ ​{​c​o​u​n​t​}​ ​条​规​则​的​图​标​？
				 * @param {number} count
				 */
				clearTitle: RequiredParams<'count'>
				/**
				 * 这​些​扩​展​名​将​回​落​到​「​文​件​默​认​图​标​」​，​规​则​本​身​保​留​。
				 */
				clearBody: string
				/**
				 * 清​空​图​标
				 */
				clearConfirm: string
				/**
				 * 已​清​空​ ​{​c​o​u​n​t​}​ ​条​规​则​的​图​标
				 * @param {number} count
				 */
				cleared: RequiredParams<'count'>
			}
			extGroup: {
				/**
				 * 移​到​分​组​…
				 */
				groupTooltip: string
				/**
				 * 管​理​分​组
				 */
				manageTooltip: string
				/**
				 * 未​分​组
				 */
				ungrouped: string
				/**
				 * {​e​x​t​s​}​ ​个​扩​展​名​ ​·​ ​{​f​i​l​e​s​}​ ​个​文​件
				 * @param {number} exts
				 * @param {number} files
				 */
				summary: RequiredParams<'exts' | 'files'>
				/**
				 * 组​内​图​标​不​一​致​，​从​此​处​重​新​选​择​即​可​统​一
				 */
				mixed: string
				/**
				 * 从​「​{​g​r​o​u​p​}​」​中​移​出​ ​.​{​e​x​t​}
				 * @param {string} ext
				 * @param {string} group
				 */
				removeTooltip: RequiredParams<'ext' | 'group'>
				/**
				 * 分​组
				 */
				label: string
				/**
				 * 分​组​名​（​留​空​则​不​分​组​）
				 */
				placeholder: string
				/**
				 * 移​到​分​组
				 */
				moveTitle: string
				/**
				 * 可​选​择​已​有​分​组​，​也​可​直​接​输​入​新​名​称​。
				 */
				moveHint: string
				/**
				 * 将​移​动​ ​{​c​o​u​n​t​}​ ​个​扩​展​名​。
				 * @param {number} count
				 */
				moveCount: RequiredParams<'count'>
				/**
				 * 留​空​即​把​这​些​扩​展​名​移​出​分​组​。
				 */
				moveOutHint: string
				/**
				 * 「​{​g​r​o​u​p​}​」​已​存​在​，​将​与​其​中​已​有​的​扩​展​名​合​并
				 * @param {string} group
				 */
				mergeWarning: RequiredParams<'group'>
				/**
				 * 已​把​ ​{​c​o​u​n​t​}​ ​个​扩​展​名​移​到​「​{​g​r​o​u​p​}​」
				 * @param {number} count
				 * @param {string} group
				 */
				moved: RequiredParams<'count' | 'group'>
				/**
				 * 已​把​ ​{​c​o​u​n​t​}​ ​个​扩​展​名​移​出​分​组
				 * @param {number} count
				 */
				movedOut: RequiredParams<'count'>
				/**
				 * 重​命​名​分​组
				 */
				renameAction: string
				/**
				 * 重​命​名​「​{​g​r​o​u​p​}​」
				 * @param {string} group
				 */
				renameTitle: RequiredParams<'group'>
				/**
				 * 该​分​组​有​ ​{​c​o​u​n​t​}​ ​个​扩​展​名​。
				 * @param {number} count
				 */
				renameCount: RequiredParams<'count'>
				/**
				 * 请​输​入​组​名​。​想​去​掉​分​组​但​保​留​规​则​，​用​「​删​除​分​组​，​保​留​规​则​」​。
				 */
				renameEmpty: string
				/**
				 * 已​把​「​{​f​r​o​m​}​」​改​名​为​「​{​t​o​}​」
				 * @param {string} from
				 * @param {string} to
				 */
				renamed: RequiredParams<'from' | 'to'>
				/**
				 * 删​除​分​组​，​保​留​规​则
				 */
				dissolveAction: string
				/**
				 * 删​除​「​{​g​r​o​u​p​}​」​？
				 * @param {string} group
				 */
				dissolveTitle: RequiredParams<'group'>
				/**
				 * 组​内​ ​{​c​o​u​n​t​}​ ​个​扩​展​名​规​则​会​保​留​下​来​，​各​自​的​图​标​不​变​，​变​成​未​分​组​。
				 * @param {number} count
				 */
				dissolveBody: RequiredParams<'count'>
				/**
				 * 删​除​分​组
				 */
				dissolveConfirm: string
				/**
				 * 已​删​除​「​{​g​r​o​u​p​}​」​，​{​c​o​u​n​t​}​ ​个​扩​展​名​转​为​未​分​组
				 * @param {number} count
				 * @param {string} group
				 */
				dissolved: RequiredParams<'count' | 'group'>
				/**
				 * 删​除​分​组​及​其​中​的​规​则
				 */
				purgeAction: string
				/**
				 * 删​除​「​{​g​r​o​u​p​}​」​及​其​中​的​规​则​？
				 * @param {string} group
				 */
				purgeTitle: RequiredParams<'group'>
				/**
				 * 这​会​删​掉​ ​{​c​o​u​n​t​}​ ​条​扩​展​名​规​则​。​这​些​扩​展​名​将​回​落​到​「​文​件​默​认​图​标​」​。
				 * @param {number} count
				 */
				purgeBody: RequiredParams<'count'>
				/**
				 * 删​除​规​则
				 */
				purgeConfirm: string
				/**
				 * 已​删​除​「​{​g​r​o​u​p​}​」​及​其​中​的​ ​{​c​o​u​n​t​}​ ​条​规​则
				 * @param {number} count
				 * @param {string} group
				 */
				purged: RequiredParams<'count' | 'group'>
				/**
				 * 「​{​g​r​o​u​p​}​」​已​不​存​在
				 * @param {string} group
				 */
				gone: RequiredParams<'group'>
				/**
				 * 从​预​设​创​建​分​组
				 */
				presetTooltip: string
				/**
				 * 从​预​设​创​建​分​组
				 */
				presetTitle: string
				/**
				 * 预​设​只​是​一​份​起​始​清​单​：​创​建​后​即​为​普​通​分​组​，​可​随​意​增​删​改​，​不​会​随​插​件​更​新​而​变​化​。
				 */
				presetHint: string
				/**
				 * 请​至​少​选​择​一​个​预​设
				 */
				presetEmpty: string
				/**
				 * 已​创​建​ ​{​g​r​o​u​p​s​}​ ​个​分​组​，​新​增​ ​{​a​d​d​e​d​}​ ​个​扩​展​名
				 * @param {number} added
				 * @param {number} groups
				 */
				presetCreated: RequiredParams<'added' | 'groups'>
				/**
				 * 并​入​已​有​规​则​ ​{​c​o​u​n​t​}​ ​个​（​图​标​保​持​不​变​）
				 * @param {number} count
				 */
				presetAdopted: RequiredParams<'count'>
				/**
				 * 跳​过​ ​{​c​o​u​n​t​}​ ​个​（​已​属​于​其​它​分​组​）​：​{​e​x​t​s​}
				 * @param {number} count
				 * @param {string} exts
				 */
				presetSkipped: RequiredParams<'count' | 'exts'>
				/**
				 * 「​{​g​r​o​u​p​}​」​已​存​在​，​将​并​入​该​分​组
				 * @param {string} group
				 */
				presetExisting: RequiredParams<'group'>
				/**
				 * 共​ ​{​t​o​t​a​l​}​ ​个​扩​展​名​，​将​新​增​ ​{​c​o​u​n​t​}​ ​个
				 * @param {number} count
				 * @param {number} total
				 */
				presetCount: RequiredParams<'count' | 'total'>
			}
			presets: {
				/**
				 * 图​片
				 */
				image: string
				/**
				 * 视​频
				 */
				video: string
				/**
				 * 音​频
				 */
				audio: string
				/**
				 * 文​档
				 */
				document: string
				/**
				 * 压​缩​包
				 */
				archive: string
				/**
				 * 代​码
				 */
				code: string
			}
			overrides: {
				/**
				 * 单​项​覆​盖
				 */
				name: string
				/**
				 * 在​文​件​树​中​右​键​文​件​/​文​件​夹​「​设​置​图​标​」​可​单​独​指​定​；​此​处​列​出​已​配​置​项
				 */
				desc: string
				/**
				 * 文​件​夹
				 */
				folderSection: string
				/**
				 * 文​件
				 */
				fileSection: string
				/**
				 * 暂​无​单​项​覆​盖
				 */
				noneFound: string
				/**
				 * 筛​选​路​径​.​.​.
				 */
				filterPlaceholder: string
				/**
				 * 没​有​匹​配​的​路​径
				 */
				noneMatched: string
			}
			menu: {
				/**
				 * 设​置​图​标
				 */
				setIcon: string
				/**
				 * 重​置​图​标
				 */
				resetIcon: string
			}
		}
		tabHeader: {
			/**
			 * 标​签​页
			 */
			name: string
			enable: {
				/**
				 * 启​用​功​能
				 */
				name: string
				/**
				 * 为​工​作​区​标​签​页​头​（​侧​栏​工​具​页​与​编​辑​器​标​签​）​自​定​义​图​标​，​两​级​解​析​：​单​标​签​优​先​（​同​名​标​签​各​配​各​的​）​、​类​型​兜​底​（​未​单​配​的​标​签​沿​用​该​类​型​统​一​图​标​）​、​未​配​置​则​保​留​原​生​。​原​生​图​标​不​会​被​删​除​，​仅​被​隐​藏​，​禁​用​后​自​动​恢​复​。
				 */
				desc: string
			}
			mapping: {
				/**
				 * 类​型​映​射
				 */
				name: string
				/**
				 * 为​视​图​类​型​（​d​a​t​a​-​t​y​p​e​）​分​配​兜​底​图​标​，​作​用​于​未​单​独​配​置​的​所​有​同​类​型​标​签​。
				 */
				desc: string
				/**
				 * 选​择​视​图​类​型​…
				 */
				selectType: string
				/**
				 * 添​加​映​射
				 */
				addTooltip: string
				/**
				 * 从​当​前​打​开​的​侧​栏​工​具​标​签​页​抓​取​类​型
				 */
				fetchTooltip: string
				/**
				 * 尚​未​配​置​类​型​映​射
				 */
				noneFound: string
				/**
				 * 删​除
				 */
				resetTooltip: string
			}
			tabs: {
				/**
				 * 单​标​签​覆​盖
				 */
				name: string
				/**
				 * 为​单​个​标​签​（​类​型​ ​+​ ​标​签​名​）​单​独​分​配​图​标​，​优​先​于​类​型​映​射​。​右​键​标​签​页​图​标​也​可​设​置​（​未​激​活​标​签​的​右​键​菜​单​只​有​原​生​项​，​先​激​活​标​签​才​会​出​现​「​设​置​图​标​」​选​项​）​。
				 */
				desc: string
				/**
				 * 选​择​标​签​…
				 */
				selectTab: string
				/**
				 * 添​加​覆​盖
				 */
				addTooltip: string
				/**
				 * 从​当​前​打​开​的​标​签​页​抓​取
				 */
				fetchTooltip: string
				/**
				 * 尚​未​配​置​单​标​签​覆​盖
				 */
				noneFound: string
				/**
				 * 删​除
				 */
				resetTooltip: string
			}
			menu: {
				/**
				 * 设​置​图​标
				 */
				setIcon: string
				/**
				 * 重​置​图​标
				 */
				resetIcon: string
			}
		}
		bookmarks: {
			/**
			 * 书​签
			 */
			name: string
			enable: {
				/**
				 * 启​用​功​能
				 */
				name: string
				/**
				 * 为​书​签​面​板​中​的​书​签​项​与​书​签​组​自​定​义​图​标​，​两​级​解​析​：​单​项​覆​盖​优​先​（​右​键​分​配​）​、​类​型​默​认​兜​底​（​按​书​签​类​型​统​一​）​、​未​配​置​则​保​留​原​生​。​叶​子​项​的​原​生​图​标​不​会​被​删​除​，​仅​被​隐​藏​，​禁​用​后​自​动​恢​复​。
				 */
				desc: string
			}
			types: {
				/**
				 * 按​类​型
				 */
				name: string
				/**
				 * 为​每​种​书​签​类​型​设​置​默​认​图​标​，​作​用​于​该​类​型​的​全​部​书​签​；​任​意​书​签​还​可​右​键​单​独​覆​盖​。
				 */
				desc: string
				/**
				 * 文​件
				 */
				file: string
				/**
				 * 文​件​夹
				 */
				folder: string
				/**
				 * 书​签​组
				 */
				group: string
				/**
				 * 搜​索
				 */
				search: string
				/**
				 * 关​系​图
				 */
				graph: string
				/**
				 * 网​址
				 */
				url: string
			}
			overrides: {
				/**
				 * 单​项​覆​盖
				 */
				name: string
				/**
				 * 在​书​签​面​板​中​右​键​任​意​书​签​「​设​置​图​标​」​可​单​独​指​定​（​六​种​类​型​均​支​持​）​；​此​处​列​出​已​配​置​项​。
				 */
				desc: string
				/**
				 * 暂​无​单​项​覆​盖
				 */
				noneFound: string
				/**
				 * 已​失​效​（​书​签​不​存​在​）
				 */
				invalid: string
			}
			menu: {
				/**
				 * 设​置​图​标
				 */
				setIcon: string
				/**
				 * 重​置​图​标
				 */
				resetIcon: string
			}
		}
		experimental: {
			/**
			 * 实​验​性
			 */
			name: string
			keepPluginFirst: {
				/**
				 * 始​终​最​先​加​载​本​插​件
				 */
				name: string
				/**
				 * 自​动​把​本​插​件​保​持​在​ ​.​o​b​s​i​d​i​a​n​/​c​o​m​m​u​n​i​t​y​-​p​l​u​g​i​n​s​.​j​s​o​n​ ​数​组​首​位​（​社​区​插​件​按​此​顺​序​加​载​）​，​避​免​其​他​插​件​因​加​载​顺​序​出​现​图​标​空​白​。​每​次​启​用​/​禁​用​插​件​后​ ​O​b​s​i​d​i​a​n​ ​会​重​写​该​数​组​，​本​功​能​会​在​本​插​件​加​载​时​自​动​修​正​。​仅​调​整​顺​序​、​不​增​删​条​目​；​对​当​前​会​话​无​效​，​下​次​启​动​生​效​。​实​验​性​功​能​，​如​出​现​异​常​请​关​闭​。
				 */
				desc: string
			}
		}
	}
	common: {
		/**
		 * 保​存
		 */
		save: string
		/**
		 * 添​加
		 */
		add: string
		/**
		 * 编​辑
		 */
		edit: string
		/**
		 * 删​除
		 */
		'delete': string
		/**
		 * 取​消
		 */
		cancel: string
		/**
		 * 在​「​{​s​o​u​r​c​e​}​」​中​随​机
		 * @param {string} source
		 */
		randomInSource: RequiredParams<'source'>
	}
	view: {
		CustomIconLib: {
			/**
			 * 自​定​义​图​标​库
			 */
			name: string
			/**
			 * 打​开​自​定​义​图​标​库
			 */
			command: string
			/**
			 * 重​新​应​用​所​有​图​标
			 */
			reapplyCommand: string
			/**
			 * 已​重​新​应​用​所​有​自​定​义​图​标
			 */
			reapplyNotice: string
			/**
			 * 搜​索​图​标​.​.​.
			 */
			searchPlaceholder: string
			/**
			 * 按​ ​/​ ​聚​焦​搜​索​，​E​s​c​ ​清​空
			 */
			searchHint: string
			density: {
				/**
				 * 网​格​密​度
				 */
				label: string
				/**
				 * 紧​凑
				 */
				compact: string
				/**
				 * 标​准
				 */
				normal: string
				/**
				 * 大
				 */
				large: string
			}
			favorites: {
				/**
				 * 收​藏
				 */
				section: string
				/**
				 * 点​图​标​右​上​角​的​ ​★​ ​或​右​键​管​理​收​藏
				 */
				hint: string
			}
			card: {
				/**
				 * 点​击​复​制​图​标​名​称
				 */
				copyNameTooltip: string
				/**
				 * 复​制​名​称
				 */
				copyName: string
				/**
				 * 复​制​完​整​ ​I​D
				 */
				copyFullId: string
				/**
				 * 复​制​图​标​名​称​失​败
				 */
				copyNameFailed: string
				/**
				 * 复​制​ ​S​V​G​ ​代​码​失​败
				 */
				copySvgCodeFailed: string
				/**
				 * 已​复​制
				 */
				copied: string
			}
			all: {
				/**
				 * 全​部
				 */
				tabName: string
				/**
				 * 输​入​关​键​词​，​跨​ ​L​u​c​i​d​e​、​我​的​ ​S​V​G​ ​与​已​安​装​图​标​包​一​起​搜​索​。
				 */
				prompt: string
				/**
				 * 跨​来​源​搜​索​结​果​按​来​源​分​组​；​点​击​图​标​可​复​制​名​称​。
				 */
				hint: string
				/**
				 * 查​看​全​部​ ​{​c​o​u​n​t​}​ ​个
				 * @param {number} count
				 */
				showAll: RequiredParams<'count'>
			}
			empty: {
				/**
				 * 没​有​匹​配​「​{​q​u​e​r​y​}​」​的​图​标
				 * @param {string} query
				 */
				noResults: RequiredParams<'query'>
				/**
				 * 清​空​搜​索
				 */
				clearSearch: string
				/**
				 * 在​ ​L​u​c​i​d​e​ ​中​搜​索​「​{​q​u​e​r​y​}​」
				 * @param {string} query
				 */
				searchInLucide: RequiredParams<'query'>
				/**
				 * 在​我​的​ ​S​V​G​ ​中​搜​索​「​{​q​u​e​r​y​}​」
				 * @param {string} query
				 */
				searchInSvg: RequiredParams<'query'>
			}
			picker: {
				/**
				 * 选​择​图​标
				 */
				title: string
				/**
				 * 搜​索​图​标​…
				 */
				searchPlaceholder: string
				segment: {
					/**
					 * 收​藏
					 */
					favorites: string
					/**
					 * 最​近​使​用
					 */
					recent: string
					/**
					 * L​u​c​i​d​e
					 */
					lucide: string
					/**
					 * 我​的​ ​S​V​G
					 */
					svg: string
				}
				/**
				 * {​c​o​u​n​t​}​ ​个​匹​配
				 * @param {number} count
				 */
				matchCount: RequiredParams<'count'>
				/**
				 * 当​前​：​{​i​d​}
				 * @param {string} id
				 */
				current: RequiredParams<'id'>
				/**
				 * 不​使​用​图​标
				 */
				clearIcon: string
				/**
				 * 加​入​收​藏
				 */
				favoriteAdd: string
				/**
				 * 取​消​收​藏
				 */
				favoriteRemove: string
				/**
				 * 颜​色
				 */
				colorLabel: string
				/**
				 * 清​除​颜​色
				 */
				colorReset: string
				/**
				 * 还​没​有​收​藏​的​图​标​。​把​常​用​图​标​点​上​ ​★​，​下​次​打​开​就​在​这​里​。
				 */
				emptyFavorites: string
				/**
				 * 还​没​有​最​近​使​用​的​图​标​，​选​过​的​会​自​动​出​现​在​这​里​。
				 */
				emptyRecent: string
				/**
				 * 该​分​组​暂​无​图​标
				 */
				emptySegment: string
				/**
				 * 该​分​组​没​有​匹​配​「​{​q​u​e​r​y​}​」​的​图​标
				 * @param {string} query
				 */
				noResults: RequiredParams<'query'>
				hint: {
					/**
					 * 移​动
					 */
					navigate: string
					/**
					 * 选​择
					 */
					select: string
					/**
					 * 切​换​分​组
					 */
					segment: string
					/**
					 * 收​藏
					 */
					favorite: string
					/**
					 * 清​除​图​标
					 */
					clear: string
					/**
					 * 关​闭
					 */
					dismiss: string
				}
			}
			svg: {
				/**
				 * 我​的​ ​S​V​G
				 */
				tabName: string
				/**
				 * 复​制​ ​S​V​G​ ​代​码
				 */
				copyAction: string
				/**
				 * 已​复​制​ ​S​V​G​ ​代​码​：​{​i​d​}
				 * @param {string} id
				 */
				copiedCode: RequiredParams<'id'>
				/**
				 * 还​没​有​自​定​义​图​标
				 */
				emptyTitle: string
				/**
				 * 粘​贴​ ​S​V​G​ ​源​码​或​上​传​ ​.​s​v​g​ ​文​件​即​可​添​加​，​添​加​后​可​在​插​件​各​处​使​用​。
				 */
				emptyDesc: string
				/**
				 * 添​加​图​标
				 */
				emptyAction: string
				sort: {
					/**
					 * 排​序
					 */
					label: string
					/**
					 * 名​称​ ​A​→​Z
					 */
					'name-asc': string
					/**
					 * 名​称​ ​Z​→​A
					 */
					'name-desc': string
					/**
					 * 最​近​添​加
					 */
					'added-desc': string
				}
				group: {
					/**
					 * 按​分​组​筛​选
					 */
					stripLabel: string
					/**
					 * 全​部
					 */
					all: string
					/**
					 * 未​分​组
					 */
					ungrouped: string
					/**
					 * 分​组
					 */
					label: string
					/**
					 * 分​组​名​（​留​空​则​不​分​组​）
					 */
					placeholder: string
					/**
					 * 可​选​择​已​有​分​组​，​也​可​直​接​输​入​新​名​称​。​留​空​则​不​归​入​任​何​分​组​。
					 */
					addHint: string
					/**
					 * 留​空​则​沿​用​文​件​中​各​图​标​自​带​的​分​组​；​填​写​则​统​一​归​入​该​分​组​。
					 */
					importHint: string
					/**
					 * 移​到​分​组​…
					 */
					moveSelected: string
					/**
					 * 移​到​分​组​…
					 */
					moveAction: string
					/**
					 * 移​到​分​组
					 */
					moveTitle: string
					/**
					 * 将​移​动​ ​{​c​o​u​n​t​}​ ​个​图​标​。
					 * @param {number} count
					 */
					moveCount: RequiredParams<'count'>
					/**
					 * 留​空​即​把​这​些​图​标​移​出​分​组​。
					 */
					moveOutHint: string
					/**
					 * 「​{​g​r​o​u​p​}​」​已​存​在​，​将​与​其​中​已​有​的​图​标​合​并
					 * @param {string} group
					 */
					mergeWarning: RequiredParams<'group'>
					/**
					 * 已​把​ ​{​c​o​u​n​t​}​ ​个​图​标​移​到​「​{​g​r​o​u​p​}​」
					 * @param {number} count
					 * @param {string} group
					 */
					moved: RequiredParams<'count' | 'group'>
					/**
					 * 已​把​ ​{​c​o​u​n​t​}​ ​个​图​标​移​出​分​组
					 * @param {number} count
					 */
					movedOut: RequiredParams<'count'>
					/**
					 * 「​{​g​r​o​u​p​}​」​里​没​有​匹​配​「​{​q​u​e​r​y​}​」​的​图​标
					 * @param {string} group
					 * @param {string} query
					 */
					noResultsInGroup: RequiredParams<'group' | 'query'>
					/**
					 * 未​分​组​里​没​有​匹​配​「​{​q​u​e​r​y​}​」​的​图​标
					 * @param {string} query
					 */
					noResultsUngrouped: RequiredParams<'query'>
					/**
					 * 在​全​部​分​组​里​搜​索
					 */
					searchAllGroups: string
					/**
					 * 右​键​分​组​标​签​可​重​命​名​或​删​除
					 */
					menuHint: string
					/**
					 * 重​命​名​分​组
					 */
					renameAction: string
					/**
					 * 重​命​名​「​{​g​r​o​u​p​}​」
					 * @param {string} group
					 */
					renameTitle: RequiredParams<'group'>
					/**
					 * 该​分​组​有​ ​{​c​o​u​n​t​}​ ​个​图​标​。
					 * @param {number} count
					 */
					renameCount: RequiredParams<'count'>
					/**
					 * 请​输​入​组​名​。​想​去​掉​分​组​但​保​留​图​标​，​用​「​删​除​分​组​，​保​留​图​标​」​。
					 */
					renameEmpty: string
					/**
					 * 已​把​「​{​f​r​o​m​}​」​改​名​为​「​{​t​o​}​」
					 * @param {string} from
					 * @param {string} to
					 */
					renamed: RequiredParams<'from' | 'to'>
					/**
					 * 删​除​分​组​，​保​留​图​标
					 */
					dissolveAction: string
					/**
					 * 删​除​「​{​g​r​o​u​p​}​」​？
					 * @param {string} group
					 */
					dissolveTitle: RequiredParams<'group'>
					/**
					 * 组​内​ ​{​c​o​u​n​t​}​ ​个​图​标​会​保​留​下​来​，​变​成​未​分​组​。
					 * @param {number} count
					 */
					dissolveBody: RequiredParams<'count'>
					/**
					 * 删​除​分​组
					 */
					dissolveConfirm: string
					/**
					 * 已​删​除​「​{​g​r​o​u​p​}​」​，​{​c​o​u​n​t​}​ ​个​图​标​转​为​未​分​组
					 * @param {number} count
					 * @param {string} group
					 */
					dissolved: RequiredParams<'count' | 'group'>
					/**
					 * 删​除​分​组​及​其​中​的​图​标
					 */
					purgeAction: string
					/**
					 * 删​除​「​{​g​r​o​u​p​}​」​及​其​中​的​图​标​？
					 * @param {string} group
					 */
					purgeTitle: RequiredParams<'group'>
					/**
					 * 这​会​真​的​删​掉​ ​{​c​o​u​n​t​}​ ​个​图​标​。​已​分​配​过​它​们​的​地​方​会​回​落​到​默​认​图​标​。
					 * @param {number} count
					 */
					purgeBody: RequiredParams<'count'>
					/**
					 * 删​除​图​标
					 */
					purgeConfirm: string
					/**
					 * 已​删​除​「​{​g​r​o​u​p​}​」​及​其​中​的​ ​{​c​o​u​n​t​}​ ​个​图​标
					 * @param {number} count
					 * @param {string} group
					 */
					purged: RequiredParams<'count' | 'group'>
					/**
					 * 「​{​g​r​o​u​p​}​」​已​不​存​在
					 * @param {string} group
					 */
					gone: RequiredParams<'group'>
				}
				exportLib: {
					/**
					 * 导​出​为​ ​J​S​O​N
					 */
					tooltip: string
					/**
					 * 已​导​出​ ​{​c​o​u​n​t​}​ ​个​图​标​到​ ​{​p​a​t​h​}
					 * @param {number} count
					 * @param {string} path
					 */
					done: RequiredParams<'count' | 'path'>
					/**
					 * 导​出​失​败
					 */
					failed: string
					/**
					 * 没​有​可​导​出​的​图​标
					 */
					empty: string
				}
				selection: {
					/**
					 * C​t​r​l​/​C​m​d​+​点​击​ ​加​选​，​S​h​i​f​t​+​点​击​ ​连​选
					 */
					hint: string
					/**
					 * 已​选​ ​{​c​o​u​n​t​}​ ​个
					 * @param {number} count
					 */
					count: RequiredParams<'count'>
					/**
					 * 删​除​所​选
					 */
					deleteSelected: string
					/**
					 * 导​出​所​选
					 */
					exportSelected: string
					/**
					 * 取​消​选​择
					 */
					clear: string
					/**
					 * 删​除​所​选​的​ ​{​c​o​u​n​t​}​ ​个​图​标​？
					 * @param {number} count
					 */
					deleteConfirm: RequiredParams<'count'>
				}
				modal: {
					/**
					 * 添​加​图​标
					 */
					addTitle: string
					/**
					 * 编​辑​图​标
					 */
					editTitle: string
					/**
					 * 粘​贴​源​码
					 */
					pasteMode: string
					/**
					 * 上​传​文​件
					 */
					uploadMode: string
					/**
					 * 导​入​ ​J​S​O​N
					 */
					importMode: string
					/**
					 * 选​择​导​出​的​ ​J​S​O​N​ ​文​件
					 */
					importPick: string
					/**
					 * 选​择​此​前​「​导​出​」​生​成​的​ ​.​j​s​o​n​ ​文​件​，​可​用​于​跨​ ​v​a​u​l​t​ ​迁​移​或​还​原​备​份​。
					 */
					importDesc: string
					/**
					 * 无​法​识​别​的​文​件​格​式​（​需​要​「​导​出​」​生​成​的​ ​J​S​O​N​）
					 */
					importInvalid: string
					/**
					 * 文​件​里​没​有​可​导​入​的​图​标
					 */
					importEmpty: string
					/**
					 * 把​ ​.​s​v​g​ ​文​件​拖​到​这​里​，​或​点​击​下​方​选​择
					 */
					dropHint: string
					/**
					 * 松​手​即​可​添​加
					 */
					dropActive: string
					/**
					 * 图​标​I​D​ ​(​例​如​:​ ​m​y​-​i​c​o​n​)
					 */
					idPlaceholder: string
					/**
					 * S​V​G​ ​内​容​ ​(​<​s​v​g​>​.​.​.​<​/​s​v​g​>​)
					 */
					contentPlaceholder: string
					/**
					 * 选​择​ ​S​V​G​ ​文​件
					 */
					selectFiles: string
					/**
					 * 可​以​选​择​多​个​ ​S​V​G​ ​文​件​进​行​批​量​添​加​，​将​使​用​文​件​名​作​为​图​标​ ​I​D​。
					 */
					selectFilesDesc: string
					/**
					 * 已​选​择​ ​{​c​o​u​n​t​}​ ​个​文​件
					 * @param {number} count
					 */
					selectedFiles: RequiredParams<'count'>
					/**
					 * 正​在​读​取​文​件​…
					 */
					reading: string
					/**
					 * 预​览
					 */
					previewTitle: string
					/**
					 * 请​填​写​图​标​ ​I​D
					 */
					idRequired: string
					/**
					 * 请​填​写​ ​S​V​G​ ​内​容
					 */
					contentRequired: string
					/**
					 * 请​至​少​选​择​一​个​ ​S​V​G​ ​文​件
					 */
					filesRequired: string
					/**
					 * 不​是​合​法​的​ ​S​V​G​（​根​元​素​必​须​是​ ​<​s​v​g​>​）
					 */
					invalidSvg: string
					/**
					 * 已​存​在​同​名​图​标​「​{​i​d​}​」
					 * @param {string} id
					 */
					duplicateId: RequiredParams<'id'>
					/**
					 * 原​图​标​已​不​存​在​（​可​能​已​在​其​它​窗​口​被​删​除​）
					 */
					targetMissing: string
					/**
					 * 重​名​处​理
					 */
					conflictLabel: string
					/**
					 * 跳​过
					 */
					conflictSkip: string
					/**
					 * 重​命​名
					 */
					conflictRename: string
					/**
					 * 覆​盖
					 */
					conflictOverwrite: string
					/**
					 * 全​部​图​标​都​与​已​有​图​标​重​名​，​没​有​可​添​加​的​内​容
					 */
					allDuplicate: string
					/**
					 * 没​有​可​解​析​为​合​法​ ​S​V​G​ ​的​文​件
					 */
					allInvalid: string
					/**
					 * 已​添​加​ ​{​c​o​u​n​t​}​ ​个
					 * @param {number} count
					 */
					resultAdded: RequiredParams<'count'>
					/**
					 * 已​覆​盖​ ​{​c​o​u​n​t​}​ ​个
					 * @param {number} count
					 */
					resultOverwritten: RequiredParams<'count'>
					/**
					 * 已​跳​过​ ​{​c​o​u​n​t​}​ ​个​重​名
					 * @param {number} count
					 */
					resultSkipped: RequiredParams<'count'>
					/**
					 * 可​添​加
					 */
					fileOk: string
					/**
					 * 重​名
					 */
					fileDuplicate: string
					/**
					 * 无​法​解​析
					 */
					fileInvalid: string
				}
			}
			pack: {
				/**
				 * 图​标​库
				 */
				tabName: string
				/**
				 * 正​在​下​载​图​标​库​…
				 */
				installing: string
				/**
				 * 正​在​下​载​图​标​ ​{​d​o​n​e​}​/​{​t​o​t​a​l​}​…
				 * @param {number} done
				 * @param {number} total
				 */
				progress: RequiredParams<'done' | 'total'>
				/**
				 * 已​安​装​ ​{​c​o​u​n​t​}​ ​个​图​标​，​立​即​生​效
				 * @param {number} count
				 */
				installed: RequiredParams<'count'>
				/**
				 * 图​标​库​安​装​失​败
				 */
				installFailed: string
				/**
				 * 已​取​消​下​载
				 */
				installCancelled: string
				/**
				 * 图​标​数
				 */
				iconCount: string
				/**
				 * 许​可​证
				 */
				licenseLabel: string
				/**
				 * 图​标​ ​I​D​ ​前​缀
				 */
				idLabel: string
				/**
				 * 来​源​包
				 */
				sourcePackage: string
				/**
				 * 该​图​标​集​包​含​ ​{​c​o​u​n​t​}​ ​个​图​标​，​体​积​较​大​，​安​装​与​同​步​耗​时​可​能​较​长​，​确​定​继​续​？
				 * @param {number} count
				 */
				bigPackWarning: RequiredParams<'count'>
				/**
				 * 安​装​完​成​后​图​标​存​储​在​本​地​，​离​线​可​用​。
				 */
				offlineHint: string
				npmModal: {
					/**
					 * 自​定​义​ ​n​p​m​ ​图​标​包
					 */
					title: string
					/**
					 * 包​ ​I​D​（​小​写​字​母​/​数​字​/​连​字​符​，​如​ ​m​y​-​i​c​o​n​s​）
					 */
					packIdPlaceholder: string
					/**
					 * n​p​m​ ​包​名​（​如​ ​@​t​a​b​l​e​r​/​i​c​o​n​s​）
					 */
					packagePlaceholder: string
					/**
					 * S​V​G​ ​路​径​ ​g​l​o​b​（​如​ ​i​c​o​n​s​/​o​u​t​l​i​n​e​/​*​.​s​v​g​）
					 */
					globPlaceholder: string
					/**
					 * 版​本​（​可​选​，​默​认​最​新​）
					 */
					versionPlaceholder: string
					/**
					 * 从​ ​n​p​m​ ​C​D​N​ ​抓​取​包​内​散​装​ ​S​V​G​ ​文​件​；​支​持​ ​*​、​*​*​ ​与​逗​号​分​组​多​选​一​语​法​。
					 */
					hint: string
					/**
					 * 包​ ​I​D​ ​需​以​小​写​字​母​开​头​，​仅​含​小​写​字​母​、​数​字​与​连​字​符
					 */
					packIdInvalid: string
					/**
					 * 该​包​ ​I​D​ ​为​保​留​字​，​请​换​一​个
					 */
					packIdReserved: string
					/**
					 * 请​填​写​ ​n​p​m​ ​包​名
					 */
					packageRequired: string
					/**
					 * 请​填​写​ ​S​V​G​ ​路​径​ ​g​l​o​b
					 */
					globRequired: string
				}
				/**
				 * 将​删​除​ ​{​c​o​u​n​t​}​ ​个​图​标​（​本​地​文​件​与​设​置​清​单​）​，​已​使​用​该​图​标​的​界​面​将​回​退​为​空​白​。
				 * @param {number} count
				 */
				uninstallHint: RequiredParams<'count'>
				/**
				 * 图​标​库​卸​载​失​败
				 */
				uninstallFailed: string
				/**
				 * 已​卸​载​「​{​n​a​m​e​}​」
				 * @param {string} name
				 */
				uninstalled: RequiredParams<'name'>
				/**
				 * 重​新​下​载
				 */
				redownload: string
				/**
				 * 从​来​源​重​新​下​载
				 */
				redownloadTooltip: string
				/**
				 * 从​来​源​重​新​拉​取​该​图​标​库​并​覆​盖​本​地​副​本​（​可​能​替​换​为​更​新​的​版​本​）​，​立​即​生​效​；​下​载​失​败​时​保​留​现​有​图​标​库​。
				 */
				redownloadHint: string
				/**
				 * 版​本
				 */
				versionLabel: string
				/**
				 * 刷​新​目​录
				 */
				refreshTooltip: string
				/**
				 * 已​安​装
				 */
				installedSection: string
				/**
				 * 尚​未​安​装​任​何​图​标​库​，​从​下​方​目​录​选​择​安​装​。
				 */
				noPacksInstalled: string
				/**
				 * {​c​o​u​n​t​}​ ​个​图​标
				 * @param {number} count
				 */
				iconCountLabel: RequiredParams<'count'>
				/**
				 * 浏​览​图​标
				 */
				browseTooltip: string
				/**
				 * 启​用​/​停​用​该​图​标​库
				 */
				enabledTooltip: string
				/**
				 * 图​标​集​目​录​（​I​c​o​n​i​f​y​，​2​2​0​+​ ​集​）
				 */
				catalogSection: string
				/**
				 * 目​录​缓​存​于​ ​{​t​i​m​e​}
				 * @param {unknown} time
				 */
				cachedAt: RequiredParams<'time'>
				/**
				 * 离​线​缓​存
				 */
				catalogCached: string
				/**
				 * 在​线
				 */
				catalogOnline: string
				/**
				 * 图​标​集​目​录​加​载​失​败​（​网​络​不​可​用​且​无​缓​存​）
				 */
				catalogLoadFailed: string
				/**
				 * 正​在​加​载​图​标​集​目​录​…
				 */
				catalogLoading: string
				catalogFilter: {
					/**
					 * 按​安​装​状​态​筛​选
					 */
					group: string
					/**
					 * 全​部
					 */
					all: string
					/**
					 * 已​安​装
					 */
					installed: string
					/**
					 * 未​安​装
					 */
					notInstalled: string
				}
				catalogSort: {
					/**
					 * 排​序
					 */
					label: string
					/**
					 * 按​名​称
					 */
					name: string
					/**
					 * 按​图​标​数
					 */
					count: string
				}
				/**
				 * 没​有​匹​配​的​图​标​包
				 */
				noMatch: string
				/**
				 * 常​用​ ​n​p​m​ ​图​标​包​（​一​键​安​装​）
				 */
				presetsSection: string
				/**
				 * 已​安​装
				 */
				alreadyInstalled: string
				/**
				 * 返​回
				 */
				backTooltip: string
				/**
				 * 只​读​展​示​。​点​击​图​标​可​复​制​完​整​ ​I​D​（​C​I​-​ ​前​缀​）​。
				 */
				detailHint: string
				/**
				 * 正​在​读​取​图​标​库​…
				 */
				detailLoading: string
				/**
				 * 预​览
				 */
				previewTitle: string
				/**
				 * 正​在​加​载​预​览​…
				 */
				previewLoading: string
				/**
				 * 暂​无​预​览​样​例
				 */
				previewEmpty: string
				/**
				 * 预​览​加​载​失​败
				 */
				previewFailed: string
				/**
				 * 显​示​更​多​（​{​s​h​o​w​n​}​/​{​t​o​t​a​l​}​）
				 * @param {number} shown
				 * @param {number} total
				 */
				showMore: RequiredParams<'shown' | 'total'>
			}
			lucide: {
				/**
				 * L​u​c​i​d​e
				 */
				tabName: string
				/**
				 * 共​ ​{​c​o​u​n​t​}​ ​个​图​标
				 * @param {number} count
				 */
				count: RequiredParams<'count'>
				/**
				 * 当​前​筛​选​下​没​有​图​标
				 */
				emptyFilter: string
				sort: {
					/**
					 * 排​序
					 */
					label: string
					/**
					 * 名​称​ ​A​→​Z
					 */
					asc: string
					/**
					 * 名​称​ ​Z​→​A
					 */
					desc: string
				}
				/**
				 * 显​示​全​部
				 */
				showAll: string
				descHints: {
					/**
					 * 插​件​内​置​的​全​部​ ​L​u​c​i​d​e​ ​图​标​（​已​去​重​）​，​点​击​图​标​可​复​制​名​称​。
					 */
					all: string
					/**
					 * O​b​s​i​d​i​a​n​ ​原​生​已​内​置​的​图​标​，​此​处​供​查​阅​对​照​，​点​击​图​标​可​复​制​名​称​。
					 */
					builtin: string
					/**
					 * 插​件​内​置​ ​L​u​c​i​d​e​ ​中​ ​O​b​s​i​d​i​a​n​ ​原​生​未​包​含​的​图​标​，​点​击​图​标​可​复​制​名​称​。
					 */
					extra: string
				}
				filter: {
					/**
					 * 筛​选​图​标
					 */
					group: string
					/**
					 * 全​部
					 */
					all: string
					/**
					 * 内​置
					 */
					builtin: string
					/**
					 * 差​异
					 */
					extra: string
				}
			}
		}
	}
}

export type TranslationFunctions = {
	settings: {
		communityPlugin: {
			/**
			 * 第三方插件
			 */
			name: () => LocalizedString
			enable: {
				/**
				 * 启用功能
				 */
				name: () => LocalizedString
				/**
				 * 为没有图标的第三方插件设置添加图标
				 */
				desc: () => LocalizedString
			}
			searchResults: {
				/**
				 * 在搜索结果中显示图标
				 */
				name: () => LocalizedString
				/**
				 * 在设置搜索结果中显示插件图标（仅在 Obsidian 1.13.0+ 生效）
				 */
				desc: () => LocalizedString
			}
			'default': {
				/**
				 * 默认图标
				 */
				name: () => LocalizedString
				/**
				 * 为没有图标的第三方插件设置添加默认图标
				 */
				desc: () => LocalizedString
				/**
				 * 重置
				 */
				resetTooltip: () => LocalizedString
			}
			search: {
				/**
				 * 输入插件名称...
				 */
				placeholder: () => LocalizedString
				/**
				 * 未找到匹配的插件
				 */
				noneFound: () => LocalizedString
				/**
				 * 重置所有为默认图标
				 */
				resetTooltip: () => LocalizedString
				/**
				 * 随机所有图标
				 */
				dicesTooltip: () => LocalizedString
			}
			pluginList: {
				/**
				 * 插件列表
				 */
				name: () => LocalizedString
				/**
				 * 为没有图标的第三方插件添加自定义图标（修复 Obsidian v1.11.0）
				 */
				desc: () => LocalizedString
				/**
				 * 重置为默认图标
				 */
				resetTooltip: () => LocalizedString
			}
		}
		ribbon: {
			/**
			 * Ribbon 侧边栏
			 */
			name: () => LocalizedString
			enable: {
				/**
				 * 启用功能
				 */
				name: () => LocalizedString
				/**
				 * 为左侧 Ribbon 按钮自定义图标
				 */
				desc: () => LocalizedString
			}
			list: {
				/**
				 * 按钮列表
				 */
				name: () => LocalizedString
				/**
				 * 为 Ribbon 按钮分配图标（按按钮提示文本识别）
				 */
				desc: () => LocalizedString
				/**
				 * 未找到 Ribbon 按钮
				 */
				noneFound: () => LocalizedString
				/**
				 * 重置为原始图标
				 */
				resetTooltip: () => LocalizedString
				/**
				 * 刷新列表
				 */
				refreshTooltip: () => LocalizedString
				/**
				 * 已有图标
				 */
				hasIcon: () => LocalizedString
				/**
				 * 无图标
				 */
				noIcon: () => LocalizedString
				/**
				 * 已自定义
				 */
				customized: () => LocalizedString
			}
		}
		fileExplorer: {
			/**
			 * 文件浏览器
			 */
			name: () => LocalizedString
			enable: {
				/**
				 * 启用功能
				 */
				name: () => LocalizedString
				/**
				 * 为文件浏览器中的文件夹和文件自定义图标
				 */
				desc: () => LocalizedString
			}
			folderDefault: {
				/**
				 * 文件夹默认图标
				 */
				name: () => LocalizedString
				/**
				 * 为所有文件夹设置统一的默认图标（留空则不显示）
				 */
				desc: () => LocalizedString
				/**
				 * 重置
				 */
				resetTooltip: () => LocalizedString
			}
			fileDefault: {
				/**
				 * 文件默认图标
				 */
				name: () => LocalizedString
				/**
				 * 为未匹配到扩展名规则的文件设置兜底图标（留空则不显示）
				 */
				desc: () => LocalizedString
				/**
				 * 重置
				 */
				resetTooltip: () => LocalizedString
			}
			inherit: {
				subfolder: {
					/**
					 * 子文件夹继承父文件夹图标
					 */
					name: () => LocalizedString
					/**
					 * 子文件夹在没有自身配置时，自动套用最近祖先文件夹的图标（含颜色）
					 */
					desc: () => LocalizedString
				}
				file: {
					/**
					 * 子文件继承父文件夹图标
					 */
					name: () => LocalizedString
					/**
					 * 文件在没有自身配置、也未匹配扩展名规则时，套用其所在文件夹链的最近图标（含颜色）
					 */
					desc: () => LocalizedString
				}
			}
			extensions: {
				/**
				 * 按扩展名
				 */
				name: () => LocalizedString
				/**
				 * 为某类扩展名的文件统一分配图标（如 pdf、canvas）；支持复合后缀，如 excalidraw.md 优先于 md。无扩展名的文件（如 .gitignore）请用下方「单项覆盖」在文件树中右键设置。
				 */
				desc: () => LocalizedString
				/**
				 * 支持批量（如 .xdb .js）...
				 */
				placeholder: () => LocalizedString
				/**
				 * 添加扩展名
				 */
				addTooltip: () => LocalizedString
				/**
				 * 尚未配置扩展名规则
				 */
				noneFound: () => LocalizedString
				/**
				 * 筛选扩展名...
				 */
				filterPlaceholder: () => LocalizedString
				/**
				 * 没有匹配的扩展名
				 */
				noneMatched: () => LocalizedString
				/**
				 * {count} 个文件
				 */
				fileCount: (arg: { count: number }) => LocalizedString
				/**
				 * 库中暂无此类文件
				 */
				noFiles: () => LocalizedString
				/**
				 * 未配置图标，此规则不生效
				 */
				needIcon: () => LocalizedString
				/**
				 * 已添加 {count} 个扩展名
				 */
				added: (arg: { count: number }) => LocalizedString
				/**
				 * 已添加 {added} 个，跳过 {skipped} 个（已存在）
				 */
				addedSkipped: (arg: { added: number, skipped: number }) => LocalizedString
				/**
				 * 这些扩展名都已配置过了
				 */
				allDuplicate: () => LocalizedString
				/**
				 * 无法识别为扩展名：{tokens}
				 */
				invalidInput: (arg: { tokens: string }) => LocalizedString
				/**
				 * 切换排序（当前：{mode}）
				 */
				sortTooltip: (arg: { mode: string }) => LocalizedString
				/**
				 * 按文件数
				 */
				sortByCount: () => LocalizedString
				/**
				 * 按名称
				 */
				sortByName: () => LocalizedString
				/**
				 * 库中还未配置的扩展名
				 */
				candidates: () => LocalizedString
				/**
				 * 添加 .{ext}（{count} 个文件）
				 */
				candidateTooltip: (arg: { count: number, ext: string }) => LocalizedString
				/**
				 * 随机筛选出的图标
				 */
				dicesTooltip: () => LocalizedString
				/**
				 * 清空筛选出的图标
				 */
				clearTooltip: () => LocalizedString
				/**
				 * 清空 {count} 条规则的图标？
				 */
				clearTitle: (arg: { count: number }) => LocalizedString
				/**
				 * 这些扩展名将回落到「文件默认图标」，规则本身保留。
				 */
				clearBody: () => LocalizedString
				/**
				 * 清空图标
				 */
				clearConfirm: () => LocalizedString
				/**
				 * 已清空 {count} 条规则的图标
				 */
				cleared: (arg: { count: number }) => LocalizedString
			}
			extGroup: {
				/**
				 * 移到分组…
				 */
				groupTooltip: () => LocalizedString
				/**
				 * 管理分组
				 */
				manageTooltip: () => LocalizedString
				/**
				 * 未分组
				 */
				ungrouped: () => LocalizedString
				/**
				 * {exts} 个扩展名 · {files} 个文件
				 */
				summary: (arg: { exts: number, files: number }) => LocalizedString
				/**
				 * 组内图标不一致，从此处重新选择即可统一
				 */
				mixed: () => LocalizedString
				/**
				 * 从「{group}」中移出 .{ext}
				 */
				removeTooltip: (arg: { ext: string, group: string }) => LocalizedString
				/**
				 * 分组
				 */
				label: () => LocalizedString
				/**
				 * 分组名（留空则不分组）
				 */
				placeholder: () => LocalizedString
				/**
				 * 移到分组
				 */
				moveTitle: () => LocalizedString
				/**
				 * 可选择已有分组，也可直接输入新名称。
				 */
				moveHint: () => LocalizedString
				/**
				 * 将移动 {count} 个扩展名。
				 */
				moveCount: (arg: { count: number }) => LocalizedString
				/**
				 * 留空即把这些扩展名移出分组。
				 */
				moveOutHint: () => LocalizedString
				/**
				 * 「{group}」已存在，将与其中已有的扩展名合并
				 */
				mergeWarning: (arg: { group: string }) => LocalizedString
				/**
				 * 已把 {count} 个扩展名移到「{group}」
				 */
				moved: (arg: { count: number, group: string }) => LocalizedString
				/**
				 * 已把 {count} 个扩展名移出分组
				 */
				movedOut: (arg: { count: number }) => LocalizedString
				/**
				 * 重命名分组
				 */
				renameAction: () => LocalizedString
				/**
				 * 重命名「{group}」
				 */
				renameTitle: (arg: { group: string }) => LocalizedString
				/**
				 * 该分组有 {count} 个扩展名。
				 */
				renameCount: (arg: { count: number }) => LocalizedString
				/**
				 * 请输入组名。想去掉分组但保留规则，用「删除分组，保留规则」。
				 */
				renameEmpty: () => LocalizedString
				/**
				 * 已把「{from}」改名为「{to}」
				 */
				renamed: (arg: { from: string, to: string }) => LocalizedString
				/**
				 * 删除分组，保留规则
				 */
				dissolveAction: () => LocalizedString
				/**
				 * 删除「{group}」？
				 */
				dissolveTitle: (arg: { group: string }) => LocalizedString
				/**
				 * 组内 {count} 个扩展名规则会保留下来，各自的图标不变，变成未分组。
				 */
				dissolveBody: (arg: { count: number }) => LocalizedString
				/**
				 * 删除分组
				 */
				dissolveConfirm: () => LocalizedString
				/**
				 * 已删除「{group}」，{count} 个扩展名转为未分组
				 */
				dissolved: (arg: { count: number, group: string }) => LocalizedString
				/**
				 * 删除分组及其中的规则
				 */
				purgeAction: () => LocalizedString
				/**
				 * 删除「{group}」及其中的规则？
				 */
				purgeTitle: (arg: { group: string }) => LocalizedString
				/**
				 * 这会删掉 {count} 条扩展名规则。这些扩展名将回落到「文件默认图标」。
				 */
				purgeBody: (arg: { count: number }) => LocalizedString
				/**
				 * 删除规则
				 */
				purgeConfirm: () => LocalizedString
				/**
				 * 已删除「{group}」及其中的 {count} 条规则
				 */
				purged: (arg: { count: number, group: string }) => LocalizedString
				/**
				 * 「{group}」已不存在
				 */
				gone: (arg: { group: string }) => LocalizedString
				/**
				 * 从预设创建分组
				 */
				presetTooltip: () => LocalizedString
				/**
				 * 从预设创建分组
				 */
				presetTitle: () => LocalizedString
				/**
				 * 预设只是一份起始清单：创建后即为普通分组，可随意增删改，不会随插件更新而变化。
				 */
				presetHint: () => LocalizedString
				/**
				 * 请至少选择一个预设
				 */
				presetEmpty: () => LocalizedString
				/**
				 * 已创建 {groups} 个分组，新增 {added} 个扩展名
				 */
				presetCreated: (arg: { added: number, groups: number }) => LocalizedString
				/**
				 * 并入已有规则 {count} 个（图标保持不变）
				 */
				presetAdopted: (arg: { count: number }) => LocalizedString
				/**
				 * 跳过 {count} 个（已属于其它分组）：{exts}
				 */
				presetSkipped: (arg: { count: number, exts: string }) => LocalizedString
				/**
				 * 「{group}」已存在，将并入该分组
				 */
				presetExisting: (arg: { group: string }) => LocalizedString
				/**
				 * 共 {total} 个扩展名，将新增 {count} 个
				 */
				presetCount: (arg: { count: number, total: number }) => LocalizedString
			}
			presets: {
				/**
				 * 图片
				 */
				image: () => LocalizedString
				/**
				 * 视频
				 */
				video: () => LocalizedString
				/**
				 * 音频
				 */
				audio: () => LocalizedString
				/**
				 * 文档
				 */
				document: () => LocalizedString
				/**
				 * 压缩包
				 */
				archive: () => LocalizedString
				/**
				 * 代码
				 */
				code: () => LocalizedString
			}
			overrides: {
				/**
				 * 单项覆盖
				 */
				name: () => LocalizedString
				/**
				 * 在文件树中右键文件/文件夹「设置图标」可单独指定；此处列出已配置项
				 */
				desc: () => LocalizedString
				/**
				 * 文件夹
				 */
				folderSection: () => LocalizedString
				/**
				 * 文件
				 */
				fileSection: () => LocalizedString
				/**
				 * 暂无单项覆盖
				 */
				noneFound: () => LocalizedString
				/**
				 * 筛选路径...
				 */
				filterPlaceholder: () => LocalizedString
				/**
				 * 没有匹配的路径
				 */
				noneMatched: () => LocalizedString
			}
			menu: {
				/**
				 * 设置图标
				 */
				setIcon: () => LocalizedString
				/**
				 * 重置图标
				 */
				resetIcon: () => LocalizedString
			}
		}
		tabHeader: {
			/**
			 * 标签页
			 */
			name: () => LocalizedString
			enable: {
				/**
				 * 启用功能
				 */
				name: () => LocalizedString
				/**
				 * 为工作区标签页头（侧栏工具页与编辑器标签）自定义图标，两级解析：单标签优先（同名标签各配各的）、类型兜底（未单配的标签沿用该类型统一图标）、未配置则保留原生。原生图标不会被删除，仅被隐藏，禁用后自动恢复。
				 */
				desc: () => LocalizedString
			}
			mapping: {
				/**
				 * 类型映射
				 */
				name: () => LocalizedString
				/**
				 * 为视图类型（data-type）分配兜底图标，作用于未单独配置的所有同类型标签。
				 */
				desc: () => LocalizedString
				/**
				 * 选择视图类型…
				 */
				selectType: () => LocalizedString
				/**
				 * 添加映射
				 */
				addTooltip: () => LocalizedString
				/**
				 * 从当前打开的侧栏工具标签页抓取类型
				 */
				fetchTooltip: () => LocalizedString
				/**
				 * 尚未配置类型映射
				 */
				noneFound: () => LocalizedString
				/**
				 * 删除
				 */
				resetTooltip: () => LocalizedString
			}
			tabs: {
				/**
				 * 单标签覆盖
				 */
				name: () => LocalizedString
				/**
				 * 为单个标签（类型 + 标签名）单独分配图标，优先于类型映射。右键标签页图标也可设置（未激活标签的右键菜单只有原生项，先激活标签才会出现「设置图标」选项）。
				 */
				desc: () => LocalizedString
				/**
				 * 选择标签…
				 */
				selectTab: () => LocalizedString
				/**
				 * 添加覆盖
				 */
				addTooltip: () => LocalizedString
				/**
				 * 从当前打开的标签页抓取
				 */
				fetchTooltip: () => LocalizedString
				/**
				 * 尚未配置单标签覆盖
				 */
				noneFound: () => LocalizedString
				/**
				 * 删除
				 */
				resetTooltip: () => LocalizedString
			}
			menu: {
				/**
				 * 设置图标
				 */
				setIcon: () => LocalizedString
				/**
				 * 重置图标
				 */
				resetIcon: () => LocalizedString
			}
		}
		bookmarks: {
			/**
			 * 书签
			 */
			name: () => LocalizedString
			enable: {
				/**
				 * 启用功能
				 */
				name: () => LocalizedString
				/**
				 * 为书签面板中的书签项与书签组自定义图标，两级解析：单项覆盖优先（右键分配）、类型默认兜底（按书签类型统一）、未配置则保留原生。叶子项的原生图标不会被删除，仅被隐藏，禁用后自动恢复。
				 */
				desc: () => LocalizedString
			}
			types: {
				/**
				 * 按类型
				 */
				name: () => LocalizedString
				/**
				 * 为每种书签类型设置默认图标，作用于该类型的全部书签；任意书签还可右键单独覆盖。
				 */
				desc: () => LocalizedString
				/**
				 * 文件
				 */
				file: () => LocalizedString
				/**
				 * 文件夹
				 */
				folder: () => LocalizedString
				/**
				 * 书签组
				 */
				group: () => LocalizedString
				/**
				 * 搜索
				 */
				search: () => LocalizedString
				/**
				 * 关系图
				 */
				graph: () => LocalizedString
				/**
				 * 网址
				 */
				url: () => LocalizedString
			}
			overrides: {
				/**
				 * 单项覆盖
				 */
				name: () => LocalizedString
				/**
				 * 在书签面板中右键任意书签「设置图标」可单独指定（六种类型均支持）；此处列出已配置项。
				 */
				desc: () => LocalizedString
				/**
				 * 暂无单项覆盖
				 */
				noneFound: () => LocalizedString
				/**
				 * 已失效（书签不存在）
				 */
				invalid: () => LocalizedString
			}
			menu: {
				/**
				 * 设置图标
				 */
				setIcon: () => LocalizedString
				/**
				 * 重置图标
				 */
				resetIcon: () => LocalizedString
			}
		}
		experimental: {
			/**
			 * 实验性
			 */
			name: () => LocalizedString
			keepPluginFirst: {
				/**
				 * 始终最先加载本插件
				 */
				name: () => LocalizedString
				/**
				 * 自动把本插件保持在 .obsidian/community-plugins.json 数组首位（社区插件按此顺序加载），避免其他插件因加载顺序出现图标空白。每次启用/禁用插件后 Obsidian 会重写该数组，本功能会在本插件加载时自动修正。仅调整顺序、不增删条目；对当前会话无效，下次启动生效。实验性功能，如出现异常请关闭。
				 */
				desc: () => LocalizedString
			}
		}
	}
	common: {
		/**
		 * 保存
		 */
		save: () => LocalizedString
		/**
		 * 添加
		 */
		add: () => LocalizedString
		/**
		 * 编辑
		 */
		edit: () => LocalizedString
		/**
		 * 删除
		 */
		'delete': () => LocalizedString
		/**
		 * 取消
		 */
		cancel: () => LocalizedString
		/**
		 * 在「{source}」中随机
		 */
		randomInSource: (arg: { source: string }) => LocalizedString
	}
	view: {
		CustomIconLib: {
			/**
			 * 自定义图标库
			 */
			name: () => LocalizedString
			/**
			 * 打开自定义图标库
			 */
			command: () => LocalizedString
			/**
			 * 重新应用所有图标
			 */
			reapplyCommand: () => LocalizedString
			/**
			 * 已重新应用所有自定义图标
			 */
			reapplyNotice: () => LocalizedString
			/**
			 * 搜索图标...
			 */
			searchPlaceholder: () => LocalizedString
			/**
			 * 按 / 聚焦搜索，Esc 清空
			 */
			searchHint: () => LocalizedString
			density: {
				/**
				 * 网格密度
				 */
				label: () => LocalizedString
				/**
				 * 紧凑
				 */
				compact: () => LocalizedString
				/**
				 * 标准
				 */
				normal: () => LocalizedString
				/**
				 * 大
				 */
				large: () => LocalizedString
			}
			favorites: {
				/**
				 * 收藏
				 */
				section: () => LocalizedString
				/**
				 * 点图标右上角的 ★ 或右键管理收藏
				 */
				hint: () => LocalizedString
			}
			card: {
				/**
				 * 点击复制图标名称
				 */
				copyNameTooltip: () => LocalizedString
				/**
				 * 复制名称
				 */
				copyName: () => LocalizedString
				/**
				 * 复制完整 ID
				 */
				copyFullId: () => LocalizedString
				/**
				 * 复制图标名称失败
				 */
				copyNameFailed: () => LocalizedString
				/**
				 * 复制 SVG 代码失败
				 */
				copySvgCodeFailed: () => LocalizedString
				/**
				 * 已复制
				 */
				copied: () => LocalizedString
			}
			all: {
				/**
				 * 全部
				 */
				tabName: () => LocalizedString
				/**
				 * 输入关键词，跨 Lucide、我的 SVG 与已安装图标包一起搜索。
				 */
				prompt: () => LocalizedString
				/**
				 * 跨来源搜索结果按来源分组；点击图标可复制名称。
				 */
				hint: () => LocalizedString
				/**
				 * 查看全部 {count} 个
				 */
				showAll: (arg: { count: number }) => LocalizedString
			}
			empty: {
				/**
				 * 没有匹配「{query}」的图标
				 */
				noResults: (arg: { query: string }) => LocalizedString
				/**
				 * 清空搜索
				 */
				clearSearch: () => LocalizedString
				/**
				 * 在 Lucide 中搜索「{query}」
				 */
				searchInLucide: (arg: { query: string }) => LocalizedString
				/**
				 * 在我的 SVG 中搜索「{query}」
				 */
				searchInSvg: (arg: { query: string }) => LocalizedString
			}
			picker: {
				/**
				 * 选择图标
				 */
				title: () => LocalizedString
				/**
				 * 搜索图标…
				 */
				searchPlaceholder: () => LocalizedString
				segment: {
					/**
					 * 收藏
					 */
					favorites: () => LocalizedString
					/**
					 * 最近使用
					 */
					recent: () => LocalizedString
					/**
					 * Lucide
					 */
					lucide: () => LocalizedString
					/**
					 * 我的 SVG
					 */
					svg: () => LocalizedString
				}
				/**
				 * {count} 个匹配
				 */
				matchCount: (arg: { count: number }) => LocalizedString
				/**
				 * 当前：{id}
				 */
				current: (arg: { id: string }) => LocalizedString
				/**
				 * 不使用图标
				 */
				clearIcon: () => LocalizedString
				/**
				 * 加入收藏
				 */
				favoriteAdd: () => LocalizedString
				/**
				 * 取消收藏
				 */
				favoriteRemove: () => LocalizedString
				/**
				 * 颜色
				 */
				colorLabel: () => LocalizedString
				/**
				 * 清除颜色
				 */
				colorReset: () => LocalizedString
				/**
				 * 还没有收藏的图标。把常用图标点上 ★，下次打开就在这里。
				 */
				emptyFavorites: () => LocalizedString
				/**
				 * 还没有最近使用的图标，选过的会自动出现在这里。
				 */
				emptyRecent: () => LocalizedString
				/**
				 * 该分组暂无图标
				 */
				emptySegment: () => LocalizedString
				/**
				 * 该分组没有匹配「{query}」的图标
				 */
				noResults: (arg: { query: string }) => LocalizedString
				hint: {
					/**
					 * 移动
					 */
					navigate: () => LocalizedString
					/**
					 * 选择
					 */
					select: () => LocalizedString
					/**
					 * 切换分组
					 */
					segment: () => LocalizedString
					/**
					 * 收藏
					 */
					favorite: () => LocalizedString
					/**
					 * 清除图标
					 */
					clear: () => LocalizedString
					/**
					 * 关闭
					 */
					dismiss: () => LocalizedString
				}
			}
			svg: {
				/**
				 * 我的 SVG
				 */
				tabName: () => LocalizedString
				/**
				 * 复制 SVG 代码
				 */
				copyAction: () => LocalizedString
				/**
				 * 已复制 SVG 代码：{id}
				 */
				copiedCode: (arg: { id: string }) => LocalizedString
				/**
				 * 还没有自定义图标
				 */
				emptyTitle: () => LocalizedString
				/**
				 * 粘贴 SVG 源码或上传 .svg 文件即可添加，添加后可在插件各处使用。
				 */
				emptyDesc: () => LocalizedString
				/**
				 * 添加图标
				 */
				emptyAction: () => LocalizedString
				sort: {
					/**
					 * 排序
					 */
					label: () => LocalizedString
					/**
					 * 名称 A→Z
					 */
					'name-asc': () => LocalizedString
					/**
					 * 名称 Z→A
					 */
					'name-desc': () => LocalizedString
					/**
					 * 最近添加
					 */
					'added-desc': () => LocalizedString
				}
				group: {
					/**
					 * 按分组筛选
					 */
					stripLabel: () => LocalizedString
					/**
					 * 全部
					 */
					all: () => LocalizedString
					/**
					 * 未分组
					 */
					ungrouped: () => LocalizedString
					/**
					 * 分组
					 */
					label: () => LocalizedString
					/**
					 * 分组名（留空则不分组）
					 */
					placeholder: () => LocalizedString
					/**
					 * 可选择已有分组，也可直接输入新名称。留空则不归入任何分组。
					 */
					addHint: () => LocalizedString
					/**
					 * 留空则沿用文件中各图标自带的分组；填写则统一归入该分组。
					 */
					importHint: () => LocalizedString
					/**
					 * 移到分组…
					 */
					moveSelected: () => LocalizedString
					/**
					 * 移到分组…
					 */
					moveAction: () => LocalizedString
					/**
					 * 移到分组
					 */
					moveTitle: () => LocalizedString
					/**
					 * 将移动 {count} 个图标。
					 */
					moveCount: (arg: { count: number }) => LocalizedString
					/**
					 * 留空即把这些图标移出分组。
					 */
					moveOutHint: () => LocalizedString
					/**
					 * 「{group}」已存在，将与其中已有的图标合并
					 */
					mergeWarning: (arg: { group: string }) => LocalizedString
					/**
					 * 已把 {count} 个图标移到「{group}」
					 */
					moved: (arg: { count: number, group: string }) => LocalizedString
					/**
					 * 已把 {count} 个图标移出分组
					 */
					movedOut: (arg: { count: number }) => LocalizedString
					/**
					 * 「{group}」里没有匹配「{query}」的图标
					 */
					noResultsInGroup: (arg: { group: string, query: string }) => LocalizedString
					/**
					 * 未分组里没有匹配「{query}」的图标
					 */
					noResultsUngrouped: (arg: { query: string }) => LocalizedString
					/**
					 * 在全部分组里搜索
					 */
					searchAllGroups: () => LocalizedString
					/**
					 * 右键分组标签可重命名或删除
					 */
					menuHint: () => LocalizedString
					/**
					 * 重命名分组
					 */
					renameAction: () => LocalizedString
					/**
					 * 重命名「{group}」
					 */
					renameTitle: (arg: { group: string }) => LocalizedString
					/**
					 * 该分组有 {count} 个图标。
					 */
					renameCount: (arg: { count: number }) => LocalizedString
					/**
					 * 请输入组名。想去掉分组但保留图标，用「删除分组，保留图标」。
					 */
					renameEmpty: () => LocalizedString
					/**
					 * 已把「{from}」改名为「{to}」
					 */
					renamed: (arg: { from: string, to: string }) => LocalizedString
					/**
					 * 删除分组，保留图标
					 */
					dissolveAction: () => LocalizedString
					/**
					 * 删除「{group}」？
					 */
					dissolveTitle: (arg: { group: string }) => LocalizedString
					/**
					 * 组内 {count} 个图标会保留下来，变成未分组。
					 */
					dissolveBody: (arg: { count: number }) => LocalizedString
					/**
					 * 删除分组
					 */
					dissolveConfirm: () => LocalizedString
					/**
					 * 已删除「{group}」，{count} 个图标转为未分组
					 */
					dissolved: (arg: { count: number, group: string }) => LocalizedString
					/**
					 * 删除分组及其中的图标
					 */
					purgeAction: () => LocalizedString
					/**
					 * 删除「{group}」及其中的图标？
					 */
					purgeTitle: (arg: { group: string }) => LocalizedString
					/**
					 * 这会真的删掉 {count} 个图标。已分配过它们的地方会回落到默认图标。
					 */
					purgeBody: (arg: { count: number }) => LocalizedString
					/**
					 * 删除图标
					 */
					purgeConfirm: () => LocalizedString
					/**
					 * 已删除「{group}」及其中的 {count} 个图标
					 */
					purged: (arg: { count: number, group: string }) => LocalizedString
					/**
					 * 「{group}」已不存在
					 */
					gone: (arg: { group: string }) => LocalizedString
				}
				exportLib: {
					/**
					 * 导出为 JSON
					 */
					tooltip: () => LocalizedString
					/**
					 * 已导出 {count} 个图标到 {path}
					 */
					done: (arg: { count: number, path: string }) => LocalizedString
					/**
					 * 导出失败
					 */
					failed: () => LocalizedString
					/**
					 * 没有可导出的图标
					 */
					empty: () => LocalizedString
				}
				selection: {
					/**
					 * Ctrl/Cmd+点击 加选，Shift+点击 连选
					 */
					hint: () => LocalizedString
					/**
					 * 已选 {count} 个
					 */
					count: (arg: { count: number }) => LocalizedString
					/**
					 * 删除所选
					 */
					deleteSelected: () => LocalizedString
					/**
					 * 导出所选
					 */
					exportSelected: () => LocalizedString
					/**
					 * 取消选择
					 */
					clear: () => LocalizedString
					/**
					 * 删除所选的 {count} 个图标？
					 */
					deleteConfirm: (arg: { count: number }) => LocalizedString
				}
				modal: {
					/**
					 * 添加图标
					 */
					addTitle: () => LocalizedString
					/**
					 * 编辑图标
					 */
					editTitle: () => LocalizedString
					/**
					 * 粘贴源码
					 */
					pasteMode: () => LocalizedString
					/**
					 * 上传文件
					 */
					uploadMode: () => LocalizedString
					/**
					 * 导入 JSON
					 */
					importMode: () => LocalizedString
					/**
					 * 选择导出的 JSON 文件
					 */
					importPick: () => LocalizedString
					/**
					 * 选择此前「导出」生成的 .json 文件，可用于跨 vault 迁移或还原备份。
					 */
					importDesc: () => LocalizedString
					/**
					 * 无法识别的文件格式（需要「导出」生成的 JSON）
					 */
					importInvalid: () => LocalizedString
					/**
					 * 文件里没有可导入的图标
					 */
					importEmpty: () => LocalizedString
					/**
					 * 把 .svg 文件拖到这里，或点击下方选择
					 */
					dropHint: () => LocalizedString
					/**
					 * 松手即可添加
					 */
					dropActive: () => LocalizedString
					/**
					 * 图标ID (例如: my-icon)
					 */
					idPlaceholder: () => LocalizedString
					/**
					 * SVG 内容 (<svg>...</svg>)
					 */
					contentPlaceholder: () => LocalizedString
					/**
					 * 选择 SVG 文件
					 */
					selectFiles: () => LocalizedString
					/**
					 * 可以选择多个 SVG 文件进行批量添加，将使用文件名作为图标 ID。
					 */
					selectFilesDesc: () => LocalizedString
					/**
					 * 已选择 {count} 个文件
					 */
					selectedFiles: (arg: { count: number }) => LocalizedString
					/**
					 * 正在读取文件…
					 */
					reading: () => LocalizedString
					/**
					 * 预览
					 */
					previewTitle: () => LocalizedString
					/**
					 * 请填写图标 ID
					 */
					idRequired: () => LocalizedString
					/**
					 * 请填写 SVG 内容
					 */
					contentRequired: () => LocalizedString
					/**
					 * 请至少选择一个 SVG 文件
					 */
					filesRequired: () => LocalizedString
					/**
					 * 不是合法的 SVG（根元素必须是 <svg>）
					 */
					invalidSvg: () => LocalizedString
					/**
					 * 已存在同名图标「{id}」
					 */
					duplicateId: (arg: { id: string }) => LocalizedString
					/**
					 * 原图标已不存在（可能已在其它窗口被删除）
					 */
					targetMissing: () => LocalizedString
					/**
					 * 重名处理
					 */
					conflictLabel: () => LocalizedString
					/**
					 * 跳过
					 */
					conflictSkip: () => LocalizedString
					/**
					 * 重命名
					 */
					conflictRename: () => LocalizedString
					/**
					 * 覆盖
					 */
					conflictOverwrite: () => LocalizedString
					/**
					 * 全部图标都与已有图标重名，没有可添加的内容
					 */
					allDuplicate: () => LocalizedString
					/**
					 * 没有可解析为合法 SVG 的文件
					 */
					allInvalid: () => LocalizedString
					/**
					 * 已添加 {count} 个
					 */
					resultAdded: (arg: { count: number }) => LocalizedString
					/**
					 * 已覆盖 {count} 个
					 */
					resultOverwritten: (arg: { count: number }) => LocalizedString
					/**
					 * 已跳过 {count} 个重名
					 */
					resultSkipped: (arg: { count: number }) => LocalizedString
					/**
					 * 可添加
					 */
					fileOk: () => LocalizedString
					/**
					 * 重名
					 */
					fileDuplicate: () => LocalizedString
					/**
					 * 无法解析
					 */
					fileInvalid: () => LocalizedString
				}
			}
			pack: {
				/**
				 * 图标库
				 */
				tabName: () => LocalizedString
				/**
				 * 正在下载图标库…
				 */
				installing: () => LocalizedString
				/**
				 * 正在下载图标 {done}/{total}…
				 */
				progress: (arg: { done: number, total: number }) => LocalizedString
				/**
				 * 已安装 {count} 个图标，立即生效
				 */
				installed: (arg: { count: number }) => LocalizedString
				/**
				 * 图标库安装失败
				 */
				installFailed: () => LocalizedString
				/**
				 * 已取消下载
				 */
				installCancelled: () => LocalizedString
				/**
				 * 图标数
				 */
				iconCount: () => LocalizedString
				/**
				 * 许可证
				 */
				licenseLabel: () => LocalizedString
				/**
				 * 图标 ID 前缀
				 */
				idLabel: () => LocalizedString
				/**
				 * 来源包
				 */
				sourcePackage: () => LocalizedString
				/**
				 * 该图标集包含 {count} 个图标，体积较大，安装与同步耗时可能较长，确定继续？
				 */
				bigPackWarning: (arg: { count: number }) => LocalizedString
				/**
				 * 安装完成后图标存储在本地，离线可用。
				 */
				offlineHint: () => LocalizedString
				npmModal: {
					/**
					 * 自定义 npm 图标包
					 */
					title: () => LocalizedString
					/**
					 * 包 ID（小写字母/数字/连字符，如 my-icons）
					 */
					packIdPlaceholder: () => LocalizedString
					/**
					 * npm 包名（如 @tabler/icons）
					 */
					packagePlaceholder: () => LocalizedString
					/**
					 * SVG 路径 glob（如 icons/outline/*.svg）
					 */
					globPlaceholder: () => LocalizedString
					/**
					 * 版本（可选，默认最新）
					 */
					versionPlaceholder: () => LocalizedString
					/**
					 * 从 npm CDN 抓取包内散装 SVG 文件；支持 *、** 与逗号分组多选一语法。
					 */
					hint: () => LocalizedString
					/**
					 * 包 ID 需以小写字母开头，仅含小写字母、数字与连字符
					 */
					packIdInvalid: () => LocalizedString
					/**
					 * 该包 ID 为保留字，请换一个
					 */
					packIdReserved: () => LocalizedString
					/**
					 * 请填写 npm 包名
					 */
					packageRequired: () => LocalizedString
					/**
					 * 请填写 SVG 路径 glob
					 */
					globRequired: () => LocalizedString
				}
				/**
				 * 将删除 {count} 个图标（本地文件与设置清单），已使用该图标的界面将回退为空白。
				 */
				uninstallHint: (arg: { count: number }) => LocalizedString
				/**
				 * 图标库卸载失败
				 */
				uninstallFailed: () => LocalizedString
				/**
				 * 已卸载「{name}」
				 */
				uninstalled: (arg: { name: string }) => LocalizedString
				/**
				 * 重新下载
				 */
				redownload: () => LocalizedString
				/**
				 * 从来源重新下载
				 */
				redownloadTooltip: () => LocalizedString
				/**
				 * 从来源重新拉取该图标库并覆盖本地副本（可能替换为更新的版本），立即生效；下载失败时保留现有图标库。
				 */
				redownloadHint: () => LocalizedString
				/**
				 * 版本
				 */
				versionLabel: () => LocalizedString
				/**
				 * 刷新目录
				 */
				refreshTooltip: () => LocalizedString
				/**
				 * 已安装
				 */
				installedSection: () => LocalizedString
				/**
				 * 尚未安装任何图标库，从下方目录选择安装。
				 */
				noPacksInstalled: () => LocalizedString
				/**
				 * {count} 个图标
				 */
				iconCountLabel: (arg: { count: number }) => LocalizedString
				/**
				 * 浏览图标
				 */
				browseTooltip: () => LocalizedString
				/**
				 * 启用/停用该图标库
				 */
				enabledTooltip: () => LocalizedString
				/**
				 * 图标集目录（Iconify，220+ 集）
				 */
				catalogSection: () => LocalizedString
				/**
				 * 目录缓存于 {time}
				 */
				cachedAt: (arg: { time: unknown }) => LocalizedString
				/**
				 * 离线缓存
				 */
				catalogCached: () => LocalizedString
				/**
				 * 在线
				 */
				catalogOnline: () => LocalizedString
				/**
				 * 图标集目录加载失败（网络不可用且无缓存）
				 */
				catalogLoadFailed: () => LocalizedString
				/**
				 * 正在加载图标集目录…
				 */
				catalogLoading: () => LocalizedString
				catalogFilter: {
					/**
					 * 按安装状态筛选
					 */
					group: () => LocalizedString
					/**
					 * 全部
					 */
					all: () => LocalizedString
					/**
					 * 已安装
					 */
					installed: () => LocalizedString
					/**
					 * 未安装
					 */
					notInstalled: () => LocalizedString
				}
				catalogSort: {
					/**
					 * 排序
					 */
					label: () => LocalizedString
					/**
					 * 按名称
					 */
					name: () => LocalizedString
					/**
					 * 按图标数
					 */
					count: () => LocalizedString
				}
				/**
				 * 没有匹配的图标包
				 */
				noMatch: () => LocalizedString
				/**
				 * 常用 npm 图标包（一键安装）
				 */
				presetsSection: () => LocalizedString
				/**
				 * 已安装
				 */
				alreadyInstalled: () => LocalizedString
				/**
				 * 返回
				 */
				backTooltip: () => LocalizedString
				/**
				 * 只读展示。点击图标可复制完整 ID（CI- 前缀）。
				 */
				detailHint: () => LocalizedString
				/**
				 * 正在读取图标库…
				 */
				detailLoading: () => LocalizedString
				/**
				 * 预览
				 */
				previewTitle: () => LocalizedString
				/**
				 * 正在加载预览…
				 */
				previewLoading: () => LocalizedString
				/**
				 * 暂无预览样例
				 */
				previewEmpty: () => LocalizedString
				/**
				 * 预览加载失败
				 */
				previewFailed: () => LocalizedString
				/**
				 * 显示更多（{shown}/{total}）
				 */
				showMore: (arg: { shown: number, total: number }) => LocalizedString
			}
			lucide: {
				/**
				 * Lucide
				 */
				tabName: () => LocalizedString
				/**
				 * 共 {count} 个图标
				 */
				count: (arg: { count: number }) => LocalizedString
				/**
				 * 当前筛选下没有图标
				 */
				emptyFilter: () => LocalizedString
				sort: {
					/**
					 * 排序
					 */
					label: () => LocalizedString
					/**
					 * 名称 A→Z
					 */
					asc: () => LocalizedString
					/**
					 * 名称 Z→A
					 */
					desc: () => LocalizedString
				}
				/**
				 * 显示全部
				 */
				showAll: () => LocalizedString
				descHints: {
					/**
					 * 插件内置的全部 Lucide 图标（已去重），点击图标可复制名称。
					 */
					all: () => LocalizedString
					/**
					 * Obsidian 原生已内置的图标，此处供查阅对照，点击图标可复制名称。
					 */
					builtin: () => LocalizedString
					/**
					 * 插件内置 Lucide 中 Obsidian 原生未包含的图标，点击图标可复制名称。
					 */
					extra: () => LocalizedString
				}
				filter: {
					/**
					 * 筛选图标
					 */
					group: () => LocalizedString
					/**
					 * 全部
					 */
					all: () => LocalizedString
					/**
					 * 内置
					 */
					builtin: () => LocalizedString
					/**
					 * 差异
					 */
					extra: () => LocalizedString
				}
			}
		}
	}
}

export type Formatters = {}
